### ISSUE TITLE
[BUG]: do not support wma in iOS

### ISSUE THREAD

**Issue by AliliWVIP** [Canardoux/flutter_sound#1022]
## Flutter Sound Version : 

- **FULL** or **LITE** flavor ?

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)

**Comment by Larpoux** [comment]
Hi @AliliWVIP ,

Please could you be more explicit ?
I do not know WMA

**Comment by AliliWVIP** [comment]
It’s an audio format developed by Microsoft. Windows Media Audiowikipedia.orgYou can get more informations from this link 在 2024年3月8日，18:55，Larpoux ***@***.***> 写道：﻿
Hi @AliliWVIP ,
Please could you be more explicit ?
I do not know WMA
