### ISSUE TITLE
[BUG]: flutter: Error initializing audio session: MissingPluginException(No implementation found for method resetPlugin on channel xyz.canardoux.flutter_sound_recorder)

### ISSUE THREAD

**Issue by Supremebosslife** [Canardoux/flutter_sound#1048]
flutter: │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:139:13)
flutter: │ #1   _AudioRecorderState.initState (package:voicepally_frontend/widgets/audio_recorder.dart:28:19)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 ctor: FlutterSoundRecorder()
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   new FlutterSoundPlayer (package:flutter_sound/public/flutter_sound_player.dart:130:13)
flutter: │ #1   _AudioRecorderState.initState (package:voicepally_frontend/widgets/audio_recorder.dart:29:17)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 ctor: FlutterSoundPlayer()
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: Opening Recorder...
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.openRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:371:13)
flutter: │ #1   _AudioRecorderState._openAudioSession (package:voicepally_frontend/widgets/audio_recorder.dart:41:26)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:---> openAudioSession
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder._openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:380:13)
flutter: │ #1   FlutterSoundRecorder.openRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:373:11)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 ---> openAudioSession
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder._openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:395:17)
flutter: │ #1   FlutterSoundRecorder.openRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:373:11)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Resetting flutter_sound Recorder Plugin
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.openRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:375:13)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:<--- openAudioSession
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: Error initializing audio session: MissingPluginException(No implementation found for method resetPlugin on channel xyz.canardoux.flutter_sound_recorder)

**Comment by Larpoux** [comment]
What platform do you use?
- Android?
- iOS?

**Comment by zhocf** [comment]
Me too, "On the Android platform, when initializing FlutterSoundRecorder recorderModule = FlutterSoundRecorder(), I encounter an error 🐛 ctor: FlutterSoundRecorder()."

**Comment by zhocf** [comment]
> What platform do you use?
> 
> * Android?
> * iOS?
> * Web?
> * Other?

Me too, "On the Android platform, when initializing FlutterSoundRecorder recorderModule = FlutterSoundRecorder(), I encounter an error 🐛 ctor: FlutterSoundRecorder()."

**Comment by Larpoux** [comment]
@zhocf : what kind of error? I need your logs.

**Comment by zhocf** [comment]
> @zhocf : what kind of error? I need your logs.

I/flutter ( 3338): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 3338): │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:139:13)
I/flutter ( 3338): │ #1   _HomePageState.startRecording (package:tape_app/view/Home/index.dart:38:43)
I/flutter ( 3338): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 3338): │ 🐛 ctor: FlutterSoundRecorder()
I/flutter ( 3338): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by Larpoux** [comment]
What kind of error do you get?

**Comment by zhocf** [comment]
> What kind of error do you get?
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
class _HomePageState extends State<HomePage> {
  FlutterSoundRecorder recorderModule = FlutterSoundRecorder();
}
I don't know what the error you mentioned is, this is the complete code, all permissions were given, and then the above error was reported

**Comment by Larpoux** [comment]
> then the above error was reported

Sorry, I don’t understand which error you have. What happens with your app? Do you get an error message?

**Comment by zhocf** [comment]
> Sorry, I don’t understand which error you have. What happens with your app? Do you get an error message?

After I ran it, there was no change in the application, and the console of Android Studio printed the following content
I/flutter (12182): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (12182): │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:139:13)
I/flutter (12182): │ #1   _HomePageState.startRecording (package:tape_app/view/Home/index.dart:37:43)
I/flutter (12182): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (12182): │ 🐛 ctor: FlutterSoundRecorder()
I/flutter (12182): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```dart
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />

class _HomePageState extends State<HomePage> {
  FlutterSoundRecorder recorderModule = FlutterSoundRecorder();

  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
       child: Container(),
      ),
    );
  }
}
```
The complete code is as above. Sorry, I don't know much more

**Comment by Larpoux** [comment]
You must do several things:
- allow recording permission (with the [permission handler](https://pub.dev/packages/permission_handler))
- Open an audio session ([with this plugin](https://pub.dev/packages/audio_session))
- Open your flutter sound recorder

You can look to the provided [example](https://github.com/Canardoux/flutter_sound/blob/master/flutter_sound/example/lib/simple_recorder/simple_recorder.dart)

**Comment by zhocf** [comment]
> ```dart
> <uses-permission android:name="android.permission.RECORD_AUDIO" />
> ```

Sorry, I mistook printing for an error. You're right. Thank you very much for your help
