### ISSUE TITLE
[BUG]: Thread 1: EXC_BAD_ACCESS (code=1, address=0x72007500740078)

### ISSUE THREAD

**Issue by Goolpe** [Canardoux/flutter_sound#1062]
## Flutter Sound Version : 

- **FULL**

├── flutter_sound 9.9.4
│   ├── flutter_sound_platform_interface...
│   ├── flutter_sound_web 9.9.4
│   │   ├── flutter_sound_platform_interface...
├── flutter_sound_platform_interface 9.9.4

----------------------------------------------------------

## Severity

- Crash

--------------------------------------------------------

## Platforms you faced the error 

- iOS (17.5.1)

- Real device (iPhone 11)

------------------------------------------------

**Describe the bug**

**To Reproduce**
We are using recorder to stream

_recorder.startRecorder(
        toStream: _recordingDataController?.sink,
        codec: Codec.pcm16,
        audioSource: AudioSource.microphone,
      );
      
 void stop(){
    await _recorder.stopRecorder();
    await _disposeRecorderStream();
  }
  
  
<img width="795" alt="Снимок экрана 2024-08-02 в 00 22 52" src="https://github.com/user-attachments/assets/069b21b5-ef28-4cdd-8ddd-06e32f9adadc">

I didn't find the way to 100% reproduce it
Just start and stop multiple times 
And on stop - the app freezes

----------------------------------------------

# Logs
<details>
<summary>Expand to see</summary>

```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.stopRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:730:13)
flutter: │ #1   SoundRecorder.cancel (package:praktika_ai_flutter/services/audio/SoundRecorder.dart:126:23)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:---> stopRecorder
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder._stopRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:740:13)
flutter: │ #1   FlutterSoundRecorder.stopRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:733:17)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:---> _stopRecorder
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder._stop (package:flutter_sound/public/flutter_sound_recorder.dart:698:13)
flutter: │ #1   FlutterSoundRecorder._stopRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:752:17)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:---> _stop
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.log (package:flutter_sound/public/flutter_sound_recorder.dart:289:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:117:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 iOS ---> stopRecorder
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.log (package:flutter_sound/public/flutter_sound_recorder.dart:289:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:117:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 iOS: ---> stopRecorder (FlautoRecorder)
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.log (package:flutter_sound/public/flutter_sound_recorder.dart:289:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:117:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 iOS: ---> stop (flautoRecorder)
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder._stop (package:flutter_sound/public/flutter_sound_recorder.dart:711:13)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:<--- _stop
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.log (package:flutter_sound/public/flutter_sound_recorder.dart:289:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:117:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 iOS: <--- stop (flautoRecorder)
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.log (package:flutter_sound/public/flutter_sound_recorder.dart:289:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:117:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 iOS: invokeMethod stopRecorderCompleted - state=0
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.stopRecorderCompleted (package:flutter_sound/public/flutter_sound_recorder.dart:236:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:89:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 ---> stopRecorderCompleted: true
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.stopRecorderCompleted (package:flutter_sound/public/flutter_sound_recorder.dart:248:13)
flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler.<anonymous closure> (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:89:24)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 <---- stopRecorderCompleted: true
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder._stopRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:756:13)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:<--- _stopRecorder :
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   FlutterSoundRecorder.stopRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:735:13)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 FS:<--- stopRecorder
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```
</details>  

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
I am going to look to that. This bug is probably serious. Perhaps it's a problem when the recorder is stopped but the driver has still data in its buffers.
I had a hard time to setup an iOS implementation working. I am going to work on this bug. Sorry for the bug

**Comment by Goolpe** [comment]
Thank you for the help, but unfortunately crash happened again with 9.9.6
Forgot to enable logs, I will try to reproduce it with logs and send them here

<img width="761" alt="Снимок экрана 2024-08-09 в 20 02 30" src="https://github.com/user-attachments/assets/2ee5585f-8480-4102-a307-b85144d7ab53">

**Comment by rRemix** [comment]
@Goolpe Have you solved this problem?

**Comment by Larpoux** [comment]
@rRemix : are you sure this is the same crash ?
Actually @Goolpe is the only user who complained about this bug.

**Comment by rRemix** [comment]
@Larpoux yes, just start and stop recorder over and over again
![image](https://github.com/user-attachments/assets/38c264c7-402e-4087-a85e-629d21fbe069)

**Comment by Larpoux** [comment]
I have no idea of the reason. Perhaps there is something which is not released correctly after each stop() and there is an overflow ? Perhaps there is a race condition with asynchronous process ?

It's very hard to debug that because the crash does not say anything useful, and we cannot reproduce the bug simply.

**Comment by rRemix** [comment]
@Larpoux  i change `getStatus() == 0` to `status == 0`, it's seem work fine. i think it's because AudioRecorderEngine was released but invoke it's method in async code block.

**Comment by weqeo** [comment]
> [@Larpoux](https://github.com/Larpoux) i change `getStatus() == 0` to `status == 0`, it's seem work fine. i think it's because AudioRecorderEngine was released but invoke it's method in async code block.

i got the same question , But I don't want to change the source code. Is there any way to do this?

**Comment by Larpoux** [comment]
> , But I don't want to change the source code.

Of course, if this patch fixes the issue, there is no reason not to include it in the regular release.

I am ashamed not to have done it since October 2024!!!
I am a poor maintainer. I am very sorry.

I will build a new release next week. Probably on Monday

**Comment by weqeo** [comment]
> > , But I don't want to change the source code.
> 
> Of course, if this patch fixes the issue, there is no reason not to include it in the regular release.
> 
> I am ashamed not to have done it since October 2024!!! I am a poor maintainer. I am very sorry.
> 
> I will build a new release next week. Probably on Monday

Please don't be so hard on yourself! We all understand that maintaining open source projects is incredibly challenging, especially when you're doing it in your spare time without compensation. Thank you for all your hard work! 🙏

**Comment by Larpoux** [comment]
@weqeo : Taudio 10.3.4 is released with the @rRemix 's patch.

### 10.3.4

- iOS : Do not call getStatus when recording to Stream because we are running async and not in the good thread. ( [fs #1062](https://github.com/Canardoux/flutter_sound/issues/1062)). Thanks to @rRemix for his/her patch.

Note: it is very simple to upgrade to Taudio 10.x : just 5 minutes!
You can look to this [simple guide](https://taudio.canardoux.xyz/tau/fs2taudio.html).

**Comment by miaotaoii** [comment]
> > , But I don't want to change the source code.
> 
> Of course, if this patch fixes the issue, there is no reason not to include it in the regular release.
> 
> I am ashamed not to have done it since October 2024!!! I am a poor maintainer. I am very sorry.
> 
> I will build a new release next week. Probably on Monday

come on. waiting for u

**Comment by weqeo** [comment]
> > [@weqeo](https://github.com/weqeo) : Taudio 10.3.4 is released with the [@rRemix](https://github.com/rRemix) 's patch.
> > ### 10.3.4
> > 
> > * iOS : Do not call getStatus when recording to Stream because we are running async and not in the good thread. ( [fs #1062](https://github.com/Canardoux/flutter_sound/issues/1062)). Thanks to [@rRemix](https://github.com/rRemix) for his/her patch.
> > 
> > Note: it is very simple to upgrade to Taudio 10.x : just 5 minutes! You can look to this [simple guide](https://taudio.canardoux.xyz/tau/fs2taudio.html).
> 
> I released 10.3.4. Please tell me if OK for you

thanks,it's working good now!

**Comment by miaotaoii** [comment]
> > [@weqeo](https://github.com/weqeo) : Taudio 10.3.4 is released with the [@rRemix](https://github.com/rRemix) 's patch.
> > ### 10.3.4
> > 
> > * iOS : Do not call getStatus when recording to Stream because we are running async and not in the good thread. ( [fs #1062](https://github.com/Canardoux/flutter_sound/issues/1062)). Thanks to [@rRemix](https://github.com/rRemix) for his/her patch.
> > 
> > Note: it is very simple to upgrade to Taudio 10.x : just 5 minutes! You can look to this [simple guide](https://taudio.canardoux.xyz/tau/fs2taudio.html).
> 
> I released 10.3.4. Please tell me if OK for you

The crash frequency seems to have decreased, but it still occurs occasionally, and the error log is different from before

thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x7000007d0036c65)
    frame #0: 0x0000000199a6d528 libobjc.A.dylib`objc_msgSend + 8
libobjc.A.dylib`objc_msgSend:
->  0x199a6d528 <+8>:  ldr    x13, [x0]
    0x199a6d52c <+12>: and    x16, x13, #0x7ffffffffffff8
    0x199a6d530 <+16>: mov    x10, x0
    0x199a6d534 <+20>: movk   x10, #0x6ae1, lsl #48

**Comment by 304164084** [comment]
<img width="1415" height="522" alt="Image" src="https://github.com/user-attachments/assets/dbdae6cd-a824-4f64-8204-6d4348dbce20" /> 
I also encountered this problem in version 9.28.0.

**Comment by Larpoux** [comment]
You can try version 10.3.4

**Comment by Larpoux** [comment]
> I reviewed the solution record for this issue and found that the condition "flautoRecoder == nil" cannot effectively detect the wild pointer problem. This is because wild pointers do have addresses and are not nil; they merely point to invalid addresses. Therefore, we need to use the weak reference feature of Objective-C to solve this problem.

Could you kindly suggest a patch? I am not an objective-C expert.

**Comment by 304164084** [comment]
The above code is handled using the "oc" method to deal with wild pointers. You can give it a try.

**Comment by miaotaoii** [comment]
> 我不喜欢这个野指针问题。我没有使用你的补丁，而是尝试移除它，`dispatch_async(dispatch_get_main_queue()`因为我很确定我们已经在主线程中了。 请尝试使用 10.3.6 版本，然后告诉我是否更好。
> 
> ## 变更日志
> ### 10.3.6
> * iOS：删除`dispatch_async(dispatch_get_main_queue()`，`/* ctor */ AudioRecorderEngine`因为当录音机快速启动/停止时会出现太多问题，而且我们已经在主线程中了

i didn't see any code change in 10.3.6 or 10.3.7 at flutter_sound_core ? where is the patch?
