### ISSUE TITLE
[HELP]:Unable to use 2 channel recording for Android device

### ISSUE THREAD

**Issue by LarryWangCA** [Canardoux/flutter_sound#1086]
I need Help for : Creating an Android and IOS app that requires 2 channels of audio streaming (using an external USB sound card

-------------------------------------
## Here is my question :

I created an app using AudioRecorder, which requires 2 channels of audio streaming (using an external USB sound card). The app works successfully on iOS. However, it does not work on Android (Sound package 9.11.2).

The audioRecorder has the following settings (**either theSource sets to defaultSource or microphone works well under the IOS platform)**:

const theSource = AudioSource.defaultSource;

    await _mRecorder!.startRecorder(
      toStream: recordingController.sink,
      codec: Codec.pcm16,
      audioSource: theSource,
      numChannels: 2,
      sampleRate: 44100,
      bufferSize: 8192,
    );

However, it always has the following error when running the app on Android platform:
<img width="1435" alt="Screenshot 2024-09-04 at 8 44 32 PM" src="https://github.com/user-attachments/assets/75fe837b-e2ad-425e-b2ed-f9858408543d">

I must use 2 channels audio recording in this project. Thank you in advance for any help.

Larry

**Comment by Larpoux** [comment]
Multi channel (stereo…) is actually not supported by Flutter Sound.
Same for float32.
There is no real reason for that. Just that nobody did it.
I actually work on Flutter Sound v10.0, and all those restrictions will be removed. But this new version is very far to be released. Probably not before next year.

**Comment by LarryWangCA** [comment]
> Multi channel (stereo…) is actually not supported by Flutter Sound. Same for float32. There is no real reason for that. Just that nobody did it. I actually work on Flutter Sound v10.0, and all those restrictions will be removed. But this new version is very far to be released. Probably not before next year.
Hi @Larpoux , Thank you for your kind reply.
I modified the code based on the provided example 'simple recorder' by only changing the channel number to 2. Actually the 2 channel recording works very well under IOS, but it has such kind of restrictions under Android which is confusing.

Since I have an urgent requirement for this project, Do you think it is easy for me to modify the package to make it support stereo recording? I never developed a package before and I have no idea how challenging it is.

Another question: Does the current flutter sound package support recording and playing at the same time? For another project, I hope to play some audio feedback based on the recorded inputs.

Thank you in advance for any help.

Best,

Larry

**Comment by Larpoux** [comment]
Not many people had ever do development inside flutter sound core.
Flutter Sound Core for Android is Java code.
I can help you to have a working dev environment and locate where is the code involved.
But unfortunately I am not sure that this will be easy for you.

Yes, there are no problems for running a player at the same time than a recorder.
There are two examples which do that (but not completely sure that the examples are perfectly working, because I was to the point to remove them because I thought that those examples was pointless).
There is also an API verb : playFromMic. But, again, not sure that it is perfectly working. I thought that playing from mic was silly and I prefer not having to maintain code which is never used.

**Comment by Larpoux** [comment]
Tomorrow, I will have a look inside Android code, and I will tell you if this is something easy to do.

**Comment by LarryWangCA** [comment]
@Larpoux Thank you for your kind help. I am looking forward to your reply.

**Comment by Larpoux** [comment]
Hi Larry
Please could you check if Flutter Sound 9.12.0 is OK for you ?

- Stereo recording on Android with Codec PCM16 [(#1086)](https://github.com/Canardoux/flutter_sound/issues/1086)
  - Stereo with Wav codec not implemented. (Simple to do if requested)
  - Number of channels > 2 is not supported
- Stereo playback on Android with codec PCM16

**Comment by LarryWangCA** [comment]
Hi @Larpoux ,Thank you for your update. I can record in stereo now on Android by using the provided example. I have the following error when updating the package for IOS. Not sure whether this is a issue on my side.

Error: The pod "flutter_sound_core" required by the plugin "flutter_sound" requires a higher minimum iOS deployment version than the plugin's
reported minimum version.
To build, remove the plugin "flutter_sound", or contact the plugin's developers for assistance.
Error: Error running pod install
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:359:7)
<asynchronous suspension>
#2      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:177:7)
<asynchronous suspension>
#3      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:43:30)
<asynchronous suspension>
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:252:3)
<asynchronous suspension>
#5      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:488:44)
<asynchronous suspension>
#6      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:533:33)
<asynchronous suspension>
#7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:55:28)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:833:27)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

**Comment by Larpoux** [comment]
Don't be surprised if actually you are having trouble to build your app : 
I am trying to install a fix, but I have many problems with gradle.
Hopefully it will be OK next hour

**Comment by LarryWangCA** [comment]
Hi @Larpoux . Thank you for your work. I tested directly plotting the stereo waveform in real time on Android. It works fine. But when I tested with my completed app (with filtering and further calculation based on stereo audio input), the UI update stucks and the input sample size is unstable. I am sure whether there is some performance-related issue with the current 9.12.0 version on Android.

**Comment by LarryWangCA** [comment]
Hi @Larpoux , Sorry for interrupting, Based on the changelog here: https://flutter-sound.canardoux.xyz/changelog.html   The latest version of flutter sound is still 9.11.3. I am wondering when 9.12.0 with Android stereo recording can be formally released? Or I should try using 9.12.44 for temporary testing?

Best,

Larry

**Comment by Larpoux** [comment]
### 9.12.44

- Trying to update gradle (8.10) and Java (22.0) to recent versions. No Succes : keep temporarly the 9.12.0 flutter_sound_core for Android

### 9.12.0

- Stereo recording on Android with Codec PCM16 [(#1086)](https://github.com/Canardoux/flutter_sound/issues/1086)
  - Stereo with Wav codec not implemented. (Simple to do if requested)
  - Number of channels > 2 is not supported
- Stereo playback on Android with codec PCM16

You can use one of those 2 versions (they are same for Android).
What is not yet merged is : 
### ???
- Fixes a stupid bug on android after seek : the current position was stucked in a wrong position [(#1087)](https://github.com/Canardoux/flutter_sound/issues/1087)

I don't think that you are very much interested by this bug fix.
I updated CHANGELOG

**Comment by Larpoux** [comment]
Oh, yes I see why the CHANGELOG is not updated.
I had a disk crash and I reset all my dev environment. But I forgot to give me the rights to access the Canardoux server.
This is simple to fix. I am going to do that immediately.
Any way : use v9.12.0 or v9.12.44

**Comment by Larpoux** [comment]
OK. The CHANGELOG is now correct

**Comment by LarryWangCA** [comment]
Hi @Larpoux , Thank you for your update. The changelog is indeed correct now. Besides, Would you please indicate which existing example demonstrates audio recording and playing at the same time? I cannot find such example for Android and IOS right now. I hope to hear immediately what I said for another project. Thank you in advance for your help.

**Comment by janoschp** [comment]
> Hi @Larpoux ,Thank you for your update. I can record in stereo now on Android by using the provided example.

@LarryWangCA which example are you talking about? I'm having trouble getting it to work.

**Comment by Larpoux** [comment]
There is nothing special to record and play at the same time. Just open the player and the recorder, and startPlayer() and startRecorder().
