### ISSUE TITLE
[HELP]:I/flutter ( 2920): │ 🐛 FS:<--- getSampleRate  I/flutter ( 2920): └ I/flutter ( 2920): │ #0   FlutterSoundRecorder._startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:625:13) I/flutter ( 2920): │ #1   FlutterSoundRecorder.startRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:593:13) I/flutter ( 2920): ├┄ I/flutter ( 2920): │ 🐛 FS:---> _startRecorder. I/flutter ( 2920): I/flutter ( 2920): Error starting recording: Instance of '_CodecNotSupportedException' usin codec default and  aacADTS

### ISSUE THREAD

**Issue by MuhammadNabeel28** [Canardoux/flutter_sound#1088]
## For example the _Element_ τ room ?

------------

I need Help for :

- Using the API ?

- Generate an iOS or Android App ?

- Debugging my App ?

- Other ?

-------------------------------------

**Comment by Larpoux** [comment]
Which platform ? iOS, Android or Web ?

**Comment by Larpoux** [comment]
Yes @MuhammadNabeel28 .
Actually I am fighting with gradle/java/jitpack.
You must use 9.12.0 until I solve that. This is a nightmare.

**Comment by Larpoux** [comment]
I did a temporary turn-around to unblock Flutter Sound users. I am going to work on this mess without bothering the FS users.

### 9.12.44

- Trying to update gradle (8.10) and Java (22.0) to recent versions. No Succes : keep temporarly the 9.12.0 flutter_sound_core for Android
