### ISSUE TITLE
I have a problem, can't get the playback error

### ISSUE THREAD

**Issue by devbravesy** [Canardoux/flutter_sound#1128]
**Package version**
9.11.2

**Environment**
Android and iOS

**Describe the bug**

If the URL of the voice being played is an invalid address, during the playback process, the external party cannot catch the playback error, and the business needs to handle the corresponding playback error. Is there any way to handle this?

log：
V/MediaHTTPService(15300): MediaHTTPService(android.media.MediaHTTPService@11fa493): Cookies: null
V/MediaHTTPService(15300): makeHTTPConnection: CookieHandler (java.net.CookieManager@ee72dba) exists.
V/MediaHTTPService(15300): makeHTTPConnection(android.media.MediaHTTPService@11fa493): cookieHandler: java.net.CookieManager@ee72dba Cookies: null
E/MediaPlayerNative(15300): error (1, -2147483648)
E/ANR_LOG (15300): >>> msg's executing time is too long

**Comment by JakeRed** [comment]
I also encountered this problem on some phones:

[okhttp]:check permission begin!
2025-12-16 17:23:32.159 21371-24328 System.out              com.ymt360.app.mass                  I  [okhttp]:not MMS!
2025-12-16 17:23:32.159 21371-24328 System.out              com.ymt360.app.mass                  I  [okhttp]:not Email!
2025-12-16 17:23:32.159 21371-24328 System.out              com.ymt360.app.mass                  I  [OkHttp] sendRequest>>
2025-12-16 17:23:32.159 21371-24328 System.out              com.ymt360.app.mass                  I  [OkHttp] sendRequest<<
2025-12-16 17:23:32.295 21371-22312 MediaHTTPConnection     com.ymt360.app.mass                  D  getSize mTotalSize=393720
2025-12-16 17:23:32.445 21371-24328 MediaPlayerNative       com.ymt360.app.mass                  W  info/warning (10110, 0)
2025-12-16 17:23:32.445 21371-24328 MediaPlayerNative       com.ymt360.app.mass                  E  error (1, -2147483648)
2025-12-16 17:23:32.449 21371-21371 Quality                 com.ymt360.app.mass                  I  Skipped: true 18 cost 305.88458 refreshRate 16636952 bit true processName com.ymt360.app.mass
2025-12-16 17:23:32.450 21371-21980 flutter                 com.ymt360.app.mass                  I  [38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[0m
2025-12-16 17:23:32.451 21371-21980 flutter                 com.ymt360.app.mass                  I  [38;5;196m│ #0   FlutterSoundPlayer.log (package:flutter_sound_lite/public/flutter_sound_player.dart:500:13)[0m
2025-12-16 17:23:32.451 21371-21980 flutter                 com.ymt360.app.mass                  I  [38;5;196m│ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:161:19)[0m
2025-12-16 17:23:32.451 21371-21980 flutter                 com.ymt360.app.mass                  I  [38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄[0m
2025-12-16 17:23:32.452 21371-21980 flutter                 com.ymt360.app.mass                  I  [38;5;196m│ ⛔ startPlayer() exception[0m
2025-12-16 17:23:32.452 21371-21980 flutter                 com.ymt360.app.mass                  I  [38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[0m
2025-12-16 17:23:32.453 21371-21980 flutter                 com.ymt360.app.mass                  I  zkhPlatformException(ERR_UNKNOWN, ERR_UNKNOWN, startPlayer() error, null)
2025-12-16 17:23:32.455 21371-21980 flutter                 com.ymt360.app.mass                  I  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.455 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #0   FlutterSoundPlayer._stopPlayer (package:flutter_sound_lite/public/flutter_sound_player.dart:1622:13)
2025-12-16 17:23:32.455 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #1   FlutterSoundPlayer.stopPlayer.<anonymous closure> (package:flutter_sound_lite/public/flutter_sound_player.dart:1617:13)
2025-12-16 17:23:32.455 21371-21980 flutter                 com.ymt360.app.mass                  I  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2025-12-16 17:23:32.455 21371-21980 flutter                 com.ymt360.app.mass                  I  │ 🐛 FS:---> _stopPlayer 
2025-12-16 17:23:32.455 21371-21980 flutter                 com.ymt360.app.mass                  I  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.457 21371-21980 flutter                 com.ymt360.app.mass                  I  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.457 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #0   FlutterSoundPlayer._stop (package:flutter_sound_lite/public/flutter_sound_player.dart:1641:13)
2025-12-16 17:23:32.457 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #1   FlutterSoundPlayer._stopPlayer (package:flutter_sound_lite/public/flutter_sound_player.dart:1633:13)
2025-12-16 17:23:32.457 21371-21980 flutter                 com.ymt360.app.mass                  I  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2025-12-16 17:23:32.457 21371-21980 flutter                 com.ymt360.app.mass                  I  │ 🐛 FS:---> _stop 
2025-12-16 17:23:32.457 21371-21980 flutter                 com.ymt360.app.mass                  I  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.459 21371-21371 MediaPlayerNative       com.ymt360.app.mass                  E  stop called in state 0, mPlayer(0xb4000075c1cc3800)
2025-12-16 17:23:32.459 21371-21371 MediaPlayerNative       com.ymt360.app.mass                  E  error (-38, 0)
2025-12-16 17:23:32.465 21371-21371 MediaPlayer             com.ymt360.app.mass                  V  resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2025-12-16 17:23:32.466 21371-21371 MediaPlayer             com.ymt360.app.mass                  V  cleanDrmObj: mDrmObj=null mDrmSessionId=null
2025-12-16 17:23:32.466 21371-21371 MediaPlayer             com.ymt360.app.mass                  V  resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2025-12-16 17:23:32.466 21371-21371 MediaPlayer             com.ymt360.app.mass                  V  cleanDrmObj: mDrmObj=null mDrmSessionId=null
2025-12-16 17:23:32.466 21371-21371 MediaPlayer             com.ymt360.app.mass                  D  _release native called
2025-12-16 17:23:32.466 21371-21371 MediaPlayer             com.ymt360.app.mass                  D  _release native finished
2025-12-16 17:23:32.469 21371-21980 flutter                 com.ymt360.app.mass                  I  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.469 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound_lite/public/flutter_sound_player.dart:436:13)
2025-12-16 17:23:32.469 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2025-12-16 17:23:32.469 21371-21980 flutter                 com.ymt360.app.mass                  I  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2025-12-16 17:23:32.470 21371-21980 flutter                 com.ymt360.app.mass                  I  │ 🐛 ---> stopPlayerCompleted: true
2025-12-16 17:23:32.470 21371-21980 flutter                 com.ymt360.app.mass                  I  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.471 21371-21980 flutter                 com.ymt360.app.mass                  I  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.471 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound_lite/public/flutter_sound_player.dart:451:13)
2025-12-16 17:23:32.471 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2025-12-16 17:23:32.471 21371-21980 flutter                 com.ymt360.app.mass                  I  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2025-12-16 17:23:32.471 21371-21980 flutter                 com.ymt360.app.mass                  I  │ 🐛 <--- stopPlayerCompleted: true
2025-12-16 17:23:32.471 21371-21980 flutter                 com.ymt360.app.mass                  I  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.478 21371-21980 flutter                 com.ymt360.app.mass                  I  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.478 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #0   FlutterSoundPlayer._stop (package:flutter_sound_lite/public/flutter_sound_player.dart:1668:13)
2025-12-16 17:23:32.478 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #1   <asynchronous suspension>
2025-12-16 17:23:32.478 21371-21980 flutter                 com.ymt360.app.mass                  I  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2025-12-16 17:23:32.478 21371-21980 flutter                 com.ymt360.app.mass                  I  │ 🐛 FS:<--- _stop 
2025-12-16 17:23:32.478 21371-21980 flutter                 com.ymt360.app.mass                  I  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.479 21371-21980 flutter                 com.ymt360.app.mass                  I  ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:32.479 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #0   FlutterSoundPlayer._stopPlayer (package:flutter_sound_lite/public/flutter_sound_player.dart:1637:13)
2025-12-16 17:23:32.479 21371-21980 flutter                 com.ymt360.app.mass                  I  │ #1   <asynchronous suspension>
2025-12-16 17:23:32.479 21371-21980 flutter                 com.ymt360.app.mass                  I  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2025-12-16 17:23:32.479 21371-21980 flutter                 com.ymt360.app.mass                  I  │ 🐛 FS:<--- stopPlayer 
2025-12-16 17:23:32.479 21371-21980 flutter                 com.ymt360.app.mass                  I  └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2025-12-16 17:23:33.733 21371-21371 TextSwitcherAnimation   com.ymt360.app.mass                  V  nextView textSwitcherWeakReference
2025-12-16 17:23:33.735 21371-21371 TextSwitcherAnimation   com.ymt360.app.mass                  V  start run ...
2025-12-16 17:23:33.755 21371-24736 System.out              com.ymt360.app.mass                  I  [okhttp]:check permission begin!
2025-12-16 17:23:33.756 21371-24736 System.out              com.ymt360.app.mass                  I  [okhttp]:not MMS!
2025-12-16 17:23:33.756 21371-24736 System.out              com.ymt360.app.mass                  I  [okhttp]:not Email!
2025-12-16 17:23:33.758 21371-24736 TrafficStats            com.ymt360.app.mass                  D  tagSocket(178) with statsTag=0xffffffff, statsUid=-1
2025-12-16 17:23:34.237 21371-24736 System.out              com.ymt360.app.mass                  I  [OkHttp] sendRequest>>
2025-12-16 17:23:34.238 21371-24736 System.out              com.ymt360.app.mass                  I  [OkHttp] sendRequest<<
