### ISSUE TITLE
[enh] Incompatibility with deeplinks

### ISSUE THREAD

**Issue by rtviwe** [Canardoux/flutter_sound#545]
## Flutter Sound Version : 

- **Released** or **Beta** version ?
Released
- Version number ?
6.4.8+2

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)
|-- flutter_sound 6.4.8+2
|   |-- flutter_sound_platform_interface 6.4.8+2
|   |-- flutter_sound_web 6.4.8+2
|   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity

- Crash ?
Yes
- Result is not what expected ?
Yes
- Cannot build my App ?
No
- Minor issue ?
No
--------------------------------------------------------

## Platforms you faced the error 

- iOS ?
Not tested
- Android ?
Yes
- Both ?
Not tested
- Emulator ? 
Yes
- Real device ?
Yes
----------------------------------------------

## Logs
```
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)
[+1368 ms] W/ActivityThread(29071): handleWindowVisibility: no activity for token android.os.BinderProxy@13823c8
[  +17 ms] D/AndroidRuntime(29071): Shutting down VM
[        ] E/AndroidRuntime(29071): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(29071): Process: com.example.stethoscope, PID: 29071
[        ] E/AndroidRuntime(29071): java.lang.AssertionError
[        ] E/AndroidRuntime(29071):     at com.dooboolab.fluttersound.FlutterSoundPlayerManager.attachFlautoPlayer(FlutterSoundPlayerManager.java:56)
[        ] E/AndroidRuntime(29071):     at com.dooboolab.fluttersound.FlutterSound.onAttachedToEngine(FlutterSound.java:46)
[        ] E/AndroidRuntime(29071):     at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:143)
[        ] E/AndroidRuntime(29071):     at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:23)
[        ] E/AndroidRuntime(29071):     at com.example.stethoscope.MainActivity.configureFlutterEngine(MainActivity.kt:25)
[        ] E/AndroidRuntime(29071):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:179)
[  +12 ms] E/AndroidRuntime(29071):     at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
[        ] E/AndroidRuntime(29071):     at android.app.Activity.performCreate(Activity.java:7820)
[        ] E/AndroidRuntime(29071):     at android.app.Activity.performCreate(Activity.java:7809)
[        ] E/AndroidRuntime(29071):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
[        ] E/AndroidRuntime(29071):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3363)
[        ] E/AndroidRuntime(29071):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
[        ] E/AndroidRuntime(29071):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
[        ] E/AndroidRuntime(29071):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime(29071):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime(29071):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
[        ] E/AndroidRuntime(29071):     at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/AndroidRuntime(29071):     at android.os.Looper.loop(Looper.java:214)
[        ] E/AndroidRuntime(29071):     at android.app.ActivityThread.main(ActivityThread.java:7710)
[   +1 ms] E/AndroidRuntime(29071):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(29071):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
[        ] E/AndroidRuntime(29071):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[  +64 ms] D/TransportRuntime.SQLiteEventStore(29071): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
[   +3 ms] D/TransportRuntime.JobInfoScheduler(29071): Scheduling upload for context TransportContext(cct, HIGHEST,
MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with
jobId=-1461439678 in 13049ms(Backend next call timestamp 1608173899145). Attempt 1
[+3093 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] executing: /Users/rtviwe/Library/Android/sdk/platform-tools/adb -s 79db564f forward --list
[   +9 ms] Exit code 0 from: /Users/rtviwe/Library/Android/sdk/platform-tools/adb -s 79db564f forward --list
[        ] 79db564f tcp:49163 tcp:42109
[   +1 ms] executing: /Users/rtviwe/Library/Android/sdk/platform-tools/adb -s 79db564f forward --remove tcp:49163
[  +13 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.stethoscope/code_cache/StethoscopeNBQDLG/Stethoscope/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +1 ms] executing: /Users/rtviwe/Library/Android/sdk/platform-tools/adb -s 79db564f forward --list
[  +10 ms] Exit code 0 from: /Users/rtviwe/Library/Android/sdk/platform-tools/adb -s 79db564f forward --list
[   +1 ms] "flutter run" took 52 555ms.
[ +242 ms] ensureAnalyticsSent: 238ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 0
```
------------------------------------------------

**Describe the bug**
After update to gradle 4.1.0 app crashes when I open deeplink

**Comment by Larpoux** [comment]
Registered in [the Flutter Sound Project](https://github.com/dooboolab/flutter_sound/projects/3)
