### ISSUE TITLE
[enh] startPlayerFromAsset()

### ISSUE THREAD

**Issue by PunnyBunny** [Canardoux/flutter_sound#549]
## Flutter Sound Version : 

- **Released** or **Beta** version ? Released

- Version number ? 6.4.2+1

- **FULL** or **LITE** flavor ? FULL

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

|-- flutter_sound 6.4.8+2
|   |-- flutter_sound_platform_interface 6.4.8+2
|   |-- flutter_sound_web 6.4.8+2
|   |   |-- flutter_sound_platform_interface...

----------------------------------------------------------

## Severity

- startPlayer exception makes unable to load sound

--------------------------------------------------------

## Platforms you faced the error 

Android real device

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

(I have no idea even after searching):
E/FlautoPlayer(25600): startPlayer() exception
E/flutter (25600): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, startPlayer() error, null)
E/flutter (25600): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (25600): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (25600): <asynchronous suspension>
E/flutter (25600): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (25600): #3      MethodChannelFlutterSoundPlayer.invokeMethod (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:161:21)
E/flutter (25600): #4      MethodChannelFlutterSoundPlayer.startPlayer (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:227:14)
E/flutter (25600): #5      FlutterSoundPlayer.startPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:870:61)
E/flutter (25600): <asynchronous suspension>
E/flutter (25600): #6      FlutterSoundPlayer.startPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart)
E/flutter (25600): #7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter (25600): #8      FlutterSoundPlayer.startPlayer (package:flutter_sound/public/flutter_sound_player.dart:852:17)
E/flutter (25600): #9      SoundManager.playUserAudioButton.<anonymous closure> (package:quiz/src/sound_manager.dart:95:32)
E/flutter (25600): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (25600): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (25600): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (25600): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (25600): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (25600): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (25600): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (25600): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (25600): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (25600): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (25600): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (25600): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (25600): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (25600): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (25600): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (25600): #25     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (25600): #26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (25600): #27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (25600): #28     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (25600): #29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (25600): #30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (25600): #31     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (25600): #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**
Compile and run with Android Studio
```import 'package:flutter/material.dart';
import 'package:flutter_sound/flutter_sound.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}


class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _audioPlayer = FlutterSoundPlayer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: playUserAudioButton()),
    );
  }

  Widget playUserAudioButton() {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: ElevatedButton(
        child: Text('test'),
        onPressed: () async {
          _audioPlayer = await _audioPlayer.openAudioSession();
          await _audioPlayer.startPlayer(fromURI: 'assets/audio/001.mp3');
        },
      ),
    );
  }
}```


**Expected behavior**
A clear and concise description of what you expected to happen.
Play the media file
-----------------------------------------------------------------

## Additional context**
Add any other context about the problem here.
The debug message is so unclear

**Comment by Carry-Lam-PK** [comment]
The problem is that I loaded the mp3 files from assets, which they don't have an URI for the player to load. Check out #23 for quick solve. I really hope they have a better error message.

**Comment by Larpoux** [comment]
Yes, this exception is really not clear.

I suggest to do tow things : 

- A clear error message when the URI is not valid
- Implement a verb 'startPlayerFromAsset()' 

Please keep this issue open, so that someone will fix that

**Comment by Carry-Lam-PK** [comment]
Agree.

**Comment by Larpoux** [comment]
Registered in [the Flutter Sound Project](https://github.com/dooboolab/flutter_sound/projects/3)

**Comment by Alvarocda** [comment]
> Yes, this exception is really not clear.
> 
> I suggest to do two things :
> 
> * A clear error message when the URI is not valid
> * Implement a verb 'startPlayerFromAsset()'
> 
> Please keep this issue open, so that someone will fix that

@Larpoux 
Do you still need someone to do this two things?
i can take a look on this if needed

**Comment by Larpoux** [comment]
Oh YES!!!.
I never refuse any help : we have many, many things to do for a better Flutter Sound and we don't have very often Pull Requests.

Actually I am (was) the only active contributor, and I work only part time on Flutter Sound. And I must confess that I am very slow to develop. So things are overflowed.

The verb 'startPlayerFromAsset()' would be a new API procedure. 
I am currently in the process of forking Flutter Sound into two branches : 
- Flutter Sound 8.4 will be published under the permissive Mozilla Public License MPL2
- Tau Sound 9.0 will be published under the strong GPL License
 
The question that you will have to answer is "Do you want to do a Pull Request against the Flutter Sound 8.3 [Master branch](https://github.com/Canardoux/tau),
or the Tau Sound 9.0 [Master branche](https://github.com/Canardoux/tau10)

**Comment by Alvarocda** [comment]
I really don't know how to answer this question. What's your recommendation?

**Comment by Larpoux** [comment]
Ι do not have any recommandation.
One of the two main differences is the License. You are the developer. This will be your work. You may decide under which License you want to publish your work.
For myself (only myself), I will not be able to maintain two forks and I want to publish all my stuff under the GPL. But this is just my choice.

The other big difference is that Tau Sound 9.0 has a new cleaner API.
You must know that there are no more many verbs like : 
- startPlayer()
- startPlayerFromBuffer()
- startPlayerFromStream()
- startPlayerFromMic()
- startPlayerFromTrack()
- And now, perhaps "startPlayerFromAsset()"

Instead, we have just a verb "play()", without many important parameters.
Before calling play(), the App calls the verb "open()".
The verb open has two parameters : 
- from:  (an object which define what must played)
- to: (an object which define on which device the playback must be done)

The object "from:" can be for example a : "InputAssetNode".
An object "InputAssetNode" will define the path of the asset.
Exemple : 
```dart
InputNode myInputNode = InputAssetNode('foo/bla');
myPlayer.open(from: myInputNode, to: OutputDeviceNode.speaker();
play()
pause()
resume()
stop()
```

**Comment by Alvarocda** [comment]
Ok, i will do my PR to Tau Sound 9.0

**Comment by Larpoux** [comment]
Yeah! Good choice 👍 .
Tau Sound 9.0 is now prety stable.
I will change a few things in the API, but nothing like a revolution.

A big thing that is actually missing in Tau Sound 9.0 is the documentation. I started to write it, but this is a painful task for me.
I will do a Push of the current documentation tomorrow.
The Doc [is/will be here](https://tau10.canardoux.xyz).

I do not want to interfere too much in your work. But if you want, I will tell you roughly what can be done.

Thank you so much for your proposition of contribution.

**Comment by Alvarocda** [comment]
> I do not want to interfere too much in your work. But if you want, I will tell you roughly what can be done.

Yes, that will be good.

> Thank you so much for your proposition of contribution.  

I want to start contributing to open source projects as I believe it's one of the best ways to improve my git, dart, flutter and programming skills and as I've already used this lib on two projects of mine I thought it would be a good place to start contributing.

**Comment by Larpoux** [comment]
This is fantastic 👍 

1. First thing to do is : 
```sh
git clone git@github.com:Canardoux/tau10.git

2. There are several places where you can load your asset : 
- The constructor of the InputAssetNode class
- The open() verb of the TauPlayer
- The play() verb of the TauPlayer

On Flutter Sound 8.3, most of the job was done in play() (startPlayerFromXXX).
I think now that it was too late, and better to do most of the job in the open() verb of TauPlayer.
But perhaps an even better place is in the InputAssetNode constructor: 
I do not like too much doing a lot of processing in a constructor, 
but still, I think that this is the good place.

[Of course you can have other ideas. Just tell me.]

When I defined the new API, I wrote a dummy class `InputAssetNode` to have a reminder of where to write the code.
This class is actually almost empty. It is in the source file tau_sound/lib/public/tau_node, line 124.

If you want to do the loading of the asset in the constructor, you must add a new member in this class to keep 
the byte buffer.
Look to the class "InputBufferNode" line 60. Probably good if the new member will also be defined as `Uint8List inputBuffer`
just like in the class `InputBufferNode`.

I suggest that the constructor will have 3 parameters : 
- The Asset name
- The Codec
- An optional TauTrack object

(look  the class InputBufferNode).


Loading the asset is very simple. You can look to the demo example, or some of the basic examples in directory : 
tau_sound/example/lib


Don't be afraid by this post. Everything is very simple and you will not have any difficulty. The problem is that I am a bad teacher and I have a very, very bad english.

**Comment by huanlirui** [comment]
How to play the local audio of the project. It's like using local pictures ？？
