### ISSUE TITLE
[problem]: Call startPlayer(fromURL:url) crash but call startPlayer(fromDataBuffer:File(url).readAsBytesSync()) won't

### ISSUE THREAD

**Issue by sweatfryash** [Canardoux/flutter_sound#650]
## Flutter Sound Version : 8.0.0+6

- **FULL** or **LITE** flavor ?

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
|-- flutter_sound 8.0.0+6
|   |-- flutter...
|   |-- flutter_sound_platform_interface 8.0.0+6
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter_sound_web 8.0.0+6
|   |   |-- flutter...
|   |   |-- flutter_sound_platform_interface...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- meta...
|   |   |   |-- typed_data...
|   |   |   '-- vector_math...
|   |   |-- js 0.6.3
|   |   '-- meta...
|   |-- flutter_spinkit 5.0.0
|   |   '-- flutter...
|   |-- logger 1.0.0
|   |-- path 1.8.0
|   |-- path_provider...
|   |-- provider 5.0.0
|   |   |-- collection...
|   |   |-- flutter...
|   |   '-- nested 1.0.0
|   |       '-- flutter...
|   |-- recase 4.0.0-nullsafety.0
|   |-- synchronized 3.0.0
|   '-- uuid 3.0.2
|       '-- crypto 3.0.0
|           |-- collection...
|           '-- typed_data...
--------------------------------------------------------
## Platforms you faced the error 
- Android 9 on Real device 
------------------------------------------------
**Describe the `bug**`
One file,if use startPlayer(fromURL) will crash,but use startPlayer(fromDataBuffer) won't,following code is my play function.
logs are in the 'logs' block
```  dart
  void startPlay(String url) {
    File file = File(url);
    // this is expected
    player.openAudioSession().then((_) {
      player.startPlayer(fromDataBuffer: file.readAsBytesSync(), codec: Codec.aacADTS,whenFinished: (){
        player.closeAudioSession();
      });
    });
    //this will crash
    player.openAudioSession().then((_) {
      player.startPlayer(fromURI: url, codec: Codec.aacADTS,whenFinished: (){
        player.closeAudioSession();
      });
    });
  }
```
following is startRecord() and stopRecord()
``` dart
  Future<void> startRecord() async {
    recorder.openAudioSession().then((_) async {
      DateTime dateTime = DateTime.now();
      final PermissionStatus permission = await PermissionHandler()
          .checkPermissionStatus(PermissionGroup.microphone);
      if (permission != PermissionStatus.granted) {
        final Map<PermissionGroup, PermissionStatus> permissions =
            await PermissionHandler().requestPermissions(
                <PermissionGroup>[PermissionGroup.microphone]);
        if (permissions[PermissionGroup.microphone] !=
            PermissionStatus.granted) {
          Toast.popToast('没有麦克风权限');
        } else {
          isRecording.value = true;
          await recorder.startRecorder(
              toFile: basePath + '/${dateTime.toString()}',
              codec: Codec.aacADTS);
        }
      } else {
        isRecording.value = true;
        await recorder.startRecorder(
            toFile: basePath + '/${dateTime.toString()}', codec: Codec.aacADTS);
      }
    });
  }

  Future<void> stopRecord() async {
    isRecording.value = false;
    String url = await recorder.stopRecorder();
    recorder.closeAudioSession();
    sounds.add(url);
    setState(() {});
    print('url::$url');
  }
```
**To Reproduce**
just call startRecord () and stopRecord() finally call startPlay()
----------------------------------------------

# Logs!!!!
logs after called that startPlayer(fromURL)
```
I/flutter (30380): FS:---> openAudioSession
I/flutter (30380): Resetting flutter_sound Player Plugin
I/AudioManager(30380): stopBluetoothSco() packageName = com.hnsi.sound_recorder
I/AudioManager(30380): In stopBluetoothSco(), calling application: com.hnsi.sound_recorder
I/AudioManager(30380): setBluetoothScoOn() on = false; packageName = com.hnsi.sound_recorder
I/AudioManager(30380): In setBluetoothScoOn(), on: false, calling application: com.hnsi.sound_recorder
I/AudioManager(30380): In setSpeakerphoneOn(), on: true, calling application: com.hnsi.sound_recorder
I/AudioManager(30380): setSpeakerphoneOn(true); packageName = com.hnsi.sound_recorder
I/AudioManager(30380): In setSpeakerphoneOn(), on: true, calling application: com.hnsi.sound_recorder
I/AudioManager(30380): setSpeakerphoneOn(true); packageName = com.hnsi.sound_recorder
I/AudioManager(30380): setBluetoothScoOn() on = false; packageName = com.hnsi.sound_recorder
I/AudioManager(30380): In setBluetoothScoOn(), on: false, calling application: com.hnsi.sound_recorder
I/AudioManager(30380): stopBluetoothSco() packageName = com.hnsi.sound_recorder
I/AudioManager(30380): In stopBluetoothSco(), calling application: com.hnsi.sound_recorder
I/AudioManager(30380): setMode: mode = 0; packageName = com.hnsi.sound_recorder
I/flutter (30380): FS:---> channelMethodCallHandler : openPlayerCompleted
I/flutter (30380): ---> openPlayerCompleted: true
I/flutter (30380): <--- openPlayerCompleted: true
I/flutter (30380): FS:<--- channelMethodCallHandler : openPlayerCompleted
I/flutter (30380): FS:<--- openAudioSession
I/flutter (30380): FS:---> startPlayer 
I/flutter (30380): FS:---> stop 
I/flutter (30380): FS:---> channelMethodCallHandler : stopPlayerCompleted
I/flutter (30380): ---> stopPlayerCompleted: true
I/flutter (30380): <--- stopPlayerCompleted: true
I/flutter (30380): FS:<--- channelMethodCallHandler : stopPlayerCompleted
I/flutter (30380): FS:<--- stop 
I/flutter (30380): FS:---> _convert 
I/flutter (30380): FS:---> needToConvert 
I/flutter (30380): FS:<--- needToConvert 
I/flutter (30380): FS:<--- _convert 
E/MediaPlayerNative(30380): error (1, -2147483648)
E/FlautoPlayer(30380): startPlayer() exception
E/flutter (30380): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, startPlayer() error, null)
E/flutter (30380): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (30380): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (30380): <asynchronous suspension>
E/flutter (30380): #2      MethodChannelFlutterSoundPlayer.invokeMethod (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:184:12)
E/flutter (30380): <asynchronous suspension>
E/flutter (30380): #3      FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:1114:19)
E/flutter (30380): <asynchronous suspension>
E/flutter (30380): #4      FlutterSoundPlayer.startPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:1044:11)
E/flutter (30380): <asynchronous suspension>
E/flutter (30380): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter (30380): <asynchronous suspension>
E/flutter (30380): #6      FlutterSoundPlayer.startPlayer (package:flutter_sound/public/flutter_sound_player.dart:1043:5)
E/flutter (30380): <asynchronous suspension>
```
-----------------------------------------------------------------

**Comment by hiashutoshsingh** [comment]
same error occurred with me today
