### ISSUE TITLE
[BUG]: crash on app start when closed via backbutton before

### ISSUE THREAD

**Issue by Bubu** [Canardoux/flutter_sound#665]
## Flutter Sound Version : 8.1.1

- **FULL** or **LITE** flavor ? LITE

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
```
|-- flutter_sound_lite 8.1.1
|   |-- flutter_sound_platform_interface 8.1.1
|   |-- flutter_sound_web 8.1.1
|   |   |-- flutter_sound_platform_interface...
```
----------------------------------------------------------

## Severity

- Crash ? Yes

--------------------------------------------------------

## Platforms you faced the error 

Android, real device, Pixel 4a
------------------------------------------------

**Describe the bug**
When closing the app via the backbutton, on reopening the app, it crash on startup. I'll gladly provide more information when necessary :).

```
--------- beginning of crash
04-07 14:20:46.753  8217  8520 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7591046420)
04-07 20:44:27.956 22601 24546 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x759221a420)
04-07 20:44:28.183 22601 22690 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-07 20:44:28.183 22601 22691 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-07 20:44:28.247 22601 22691 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 22691 (hwuiTask1), pid 22601 (om.famedly.talk)
04-08 17:42:14.947 22971 23522 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7591ed2420)
04-08 21:28:43.638  8715  8866 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7592157420)
04-08 21:28:43.638  8715  8866 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8866 (DartWorker), pid 8715 (om.famedly.talk)
04-08 21:28:43.771  8715  8834 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-08 21:28:43.771  8715  8835 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-08 21:28:43.795  8899  8899 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-08 21:28:43.795  8899  8899 F DEBUG   : Build fingerprint: 'google/sunfish/sunfish:11/RQ2A.210305.006/7119741:user/release-keys'
04-08 21:28:43.795  8899  8899 F DEBUG   : Revision: 'MP1.0'
04-08 21:28:43.795  8899  8899 F DEBUG   : ABI: 'arm64'
04-08 21:28:43.795  8899  8899 F DEBUG   : Timestamp: 2021-04-08 21:28:43+0200
04-08 21:28:43.795  8899  8899 F DEBUG   : pid: 8715, tid: 8866, name: DartWorker  >>> com.famedly.talk <<<
04-08 21:28:43.795  8899  8899 F DEBUG   : uid: 10319
04-08 21:28:43.795  8899  8899 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
04-08 21:28:43.795  8899  8899 F DEBUG   : Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7592157420)'
04-08 21:28:43.795  8899  8899 F DEBUG   :     x0  0000000000000000  x1  00000000000022a2  x2  0000000000000006  x3  000000754eef4e40
04-08 21:28:43.795  8899  8899 F DEBUG   :     x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
04-08 21:28:43.795  8899  8899 F DEBUG   :     x8  00000000000000f0  x9  cadb2cc212ae78a9  x10 0000000000000000  x11 ffffffc0fffffbdf
04-08 21:28:43.795  8899  8899 F DEBUG   :     x12 0000000000000001  x13 000002ed99c3a3e5  x14 0025ef149a1e92ab  x15 0000000001ed0b9c
04-08 21:28:43.795  8899  8899 F DEBUG   :     x16 000000789ae0ac80  x17 000000789adec870  x18 000000754e498000  x19 000000000000220b
04-08 21:28:43.795  8899  8899 F DEBUG   :     x20 00000000000022a2  x21 00000000ffffffff  x22 000000759202ab48  x23 0000007592028b90
04-08 21:28:43.795  8899  8899 F DEBUG   :     x24 000000757f18ced1  x25 000000754ee13000  x26 b4000077465fd300  x27 000000757f190730
04-08 21:28:43.795  8899  8899 F DEBUG   :     x28 0000000000000004  x29 000000754eef4ec0
04-08 21:28:43.795  8899  8899 F DEBUG   :     lr  000000789ada02a0  sp  000000754eef4e20  pc  000000789ada02cc  pst 0000000000000000
04-08 22:06:56.562 10770 11533 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7592de2420)
04-08 22:06:56.562 10770 11533 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 11533 (DartWorker), pid 10770 (om.famedly.talk)
04-08 22:06:56.678 10770 10869 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-08 22:06:56.679 10770 10870 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-08 22:06:56.687 11539 11539 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-08 22:06:56.687 11539 11539 F DEBUG   : Build fingerprint: 'google/sunfish/sunfish:11/RQ2A.210305.006/7119741:user/release-keys'
04-08 22:06:56.687 11539 11539 F DEBUG   : Revision: 'MP1.0'
04-08 22:06:56.687 11539 11539 F DEBUG   : ABI: 'arm64'
04-08 22:06:56.688 11539 11539 F DEBUG   : Timestamp: 2021-04-08 22:06:56+0200
04-08 22:06:56.688 11539 11539 F DEBUG   : pid: 10770, tid: 11533, name: DartWorker  >>> com.famedly.talk <<<
04-08 22:06:56.688 11539 11539 F DEBUG   : uid: 10319
04-08 22:06:56.688 11539 11539 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
04-08 22:06:56.688 11539 11539 F DEBUG   : Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7592de2420)'
04-08 22:06:56.688 11539 11539 F DEBUG   :     x0  0000000000000000  x1  0000000000002d0d  x2  0000000000000006  x3  00000075f53fae40
04-08 22:06:56.688 11539 11539 F DEBUG   :     x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
04-08 22:06:56.688 11539 11539 F DEBUG   :     x8  00000000000000f0  x9  cadb2cc212ae78a9  x10 0000000000000000  x11 ffffffc0fffffbdf
04-08 22:06:56.688 11539 11539 F DEBUG   :     x12 0000000000000001  x13 000002f7d9ce90b3  x14 002161c74633f2d3  x15 0000000001f4c0d0
04-08 22:06:56.688 11539 11539 F DEBUG   :     x16 000000789ae0ac80  x17 000000789adec870  x18 00000075962e8000  x19 0000000000002a12
04-08 22:06:56.688 11539 11539 F DEBUG   :     x20 0000000000002d0d  x21 00000000ffffffff  x22 0000007592cb5b48  x23 0000007592cb3b90
04-08 22:06:56.688 11539 11539 F DEBUG   :     x24 000000757f20ced1  x25 00000075f5319000  x26 b4000077465e40d0  x27 000000757f210730
04-08 22:06:56.688 11539 11539 F DEBUG   :     x28 0000000000000004  x29 00000075f53faec0
04-08 22:06:56.688 11539 11539 F DEBUG   :     lr  000000789ada02a0  sp  00000075f53fae20  pc  000000789ada02cc  pst 0000000000000000
04-21 16:05:29.278 29965 30883 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7594869420)
04-21 16:05:29.279 29965 30883 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 30883 (DartWorker), pid 29965 (om.famedly.talk)
04-21 16:05:29.403 29965 30156 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-21 16:05:29.403 29965 30157 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7899c79f70)
04-21 16:05:29.427 30888 30888 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-21 16:05:29.428 30888 30888 F DEBUG   : Build fingerprint: 'google/sunfish/sunfish:11/RQ2A.210305.006/7119741:user/release-keys'
04-21 16:05:29.428 30888 30888 F DEBUG   : Revision: 'MP1.0'
04-21 16:05:29.428 30888 30888 F DEBUG   : ABI: 'arm64'
04-21 16:05:29.428 30888 30888 F DEBUG   : Timestamp: 2021-04-21 16:05:29+0200
04-21 16:05:29.428 30888 30888 F DEBUG   : pid: 29965, tid: 30883, name: DartWorker  >>> com.famedly.talk <<<
04-21 16:05:29.428 30888 30888 F DEBUG   : uid: 10319
04-21 16:05:29.428 30888 30888 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
04-21 16:05:29.428 30888 30888 F DEBUG   : Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7594869420)'
04-21 16:05:29.428 30888 30888 F DEBUG   :     x0  0000000000000000  x1  00000000000078a3  x2  0000000000000006  x3  00000075f767ae40
04-21 16:05:29.428 30888 30888 F DEBUG   :     x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
04-21 16:05:29.428 30888 30888 F DEBUG   :     x8  00000000000000f0  x9  cadb2cc212ae78a9  x10 0000000000000000  x11 ffffffc0fffffbdf
04-21 16:05:29.428 30888 30888 F DEBUG   :     x12 0000000000000001  x13 00001634019d89ca  x14 0010539bd2c7f527  x15 0000000003214d56
04-21 16:05:29.428 30888 30888 F DEBUG   :     x16 000000789ae0ac80  x17 000000789adec870  x18 0000007581ae2000  x19 000000000000750d
04-21 16:05:29.428 30888 30888 F DEBUG   :     x20 00000000000078a3  x21 00000000ffffffff  x22 000000759473cb48  x23 000000759473ab90
04-21 16:05:29.428 30888 30888 F DEBUG   :     x24 0000007584c0ced1  x25 00000075f7599000  x26 b4000077465f9610  x27 0000007584c10730
04-21 16:05:29.428 30888 30888 F DEBUG   :     x28 0000000000000004  x29 00000075f767aec0
04-21 16:05:29.428 30888 30888 F DEBUG   :     lr  000000789ada02a0  sp  00000075f767ae20  pc  000000789ada02cc  pst 0000000000000000
04-21 18:18:22.639 31577 31577 E AndroidRuntime: FATAL EXCEPTION: main
04-21 18:18:22.639 31577 31577 E AndroidRuntime: Process: com.famedly.talk, PID: 31577
04-21 18:18:22.639 31577 31577 E AndroidRuntime: java.lang.AssertionError
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at com.dooboolab.fluttersound.FlutterSoundPlayerManager.attachFlautoPlayer(FlutterSoundPlayerManager.java:56)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at com.dooboolab.fluttersound.FlutterSound.onAttachedToActivity(FlutterSound.java:102)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:362)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:344)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:169)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at com.famedly.talk.MainActivity.onCreate(MainActivity.kt:13)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-21 18:18:22.639 31577 31577 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by chainchelliah** [comment]
I'm also getting the same issue. Definitely a bug.

**Comment by Larpoux** [comment]
Flutter Sound 8.1.3 integrates a Pull Request kindly provided by @aaassseee.
Thanks to him.
