### ISSUE TITLE
[HELP]: MissingPluginException

### ISSUE THREAD

**Issue by sergiyvergun01** [Canardoux/flutter_sound#752]
I'm using flutter_sound_lite and that's the issue I see when try to play the recording:

```
E/flutter (15514): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method executeFFmpegWithArguments on channel flutter_sound_ffmpeg)
E/flutter (15514): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (15514): <asynchronous suspension>
E/flutter (15514): #1      FlutterSoundFFmpeg.executeWithArguments (package:flutter_sound_lite/public/util/flutter_sound_ffmpeg.dart:589:20)
E/flutter (15514): <asynchronous suspension>
E/flutter (15514): #2      FlutterSoundHelper.convertFile (package:flutter_sound_lite/public/util/flutter_sound_helper.dart:307:12)
E/flutter (15514): <asynchronous suspension>
E/flutter (15514): #3      _AudioRecorderPageState.play (package:flutter_companion/features/audio_recorder_page.dart:105:5)
E/flutter (15514): <asynchronous suspension>
```

How to fix this?

**Comment by Larpoux** [comment]
Your code is calling `FlutterSoundHelper.convertFile ()` either explicitly or indirectly.
This function is not implemented in the LITE flavor of Flutter Sound.

If you need this function you must switch to the FULL flavor

**Comment by vernalclareai** [comment]
Hi,  FlutterSoundHelper().convertFile  function is removed  in the flutter_sound 9.2.12.
How can I replace the function ?
bc I need to convert opus file to mp3 on my app.
I was using the 8.5.0 version before.
Thanks.

**Comment by Larpoux** [comment]
You can use the Flutter plugin [ffmpeg kit](https://pub.dev/packages/ffmpeg_kit_flutter)

**Comment by vernalclareai** [comment]
okay, thanks 
I will try with the plugin.
