### ISSUE TITLE
[BUG]:Cannot run Flutter 2.5 app on simulator with flutter_sound

### ISSUE THREAD

**Issue by tkeithblack** [Canardoux/flutter_sound#775]
## Flutter Sound Version : flutter_sound 8.14 through 8.3.12 (I've tried various versions)

- **FULL**

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```
FINE: Pub 2.14.2
    | |-- flutter_sound 8.3.12
    | |   |-- flutter_sound_platform_interface 8.3.12
    | |   |-- flutter_sound_web 8.3.12
    | |   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity

- Cannot build my App

--------------------------------------------------------

## Platforms you faced the error 

- iOS Simulator Version 12.5.1 (961.1)

------------------------------------------------

**Describe the bug**
When I build a flutter app using **flutter 2.5.1** and I include **flutter_sound**, the app will not run on the simulator using the **flutter run** command. However, if I use **flutter run** and direct execution to a physical device it does run.

Furthermore, if I run the app from XCode and target the simulator it will run.

I have been using flutter_sound for about a year on other versions of flutter, however, when I upgraded to flutter 2.5 this started happening. I then rolled back to flutter 2.1.3 and the issue stopped occurring. After upgrading to flutter 2.5 again the issue started occurring again.

I have been through many many cycles of deleting caches, DerivedData, flutter clean, etc. etc. to no avail.

**To Reproduce**
1. Create a new counter app (default flutter app)
2. Add flutter_sound 8.3.12 to the Pubspec.yaml file
3. Build the file using flutter run and target the iOS simulator.
4. Below is a preview of the output, look at the attached log for the full verbose output:

(_notice the references to mobile-ffmpeg-audio and building for iOS Simulator_):

```
/Users/keithblack/Library/Developer/Xcode/DerivedData/Runner-gejpisazgavnwcdkopckhpbmbxgn/Build/Intermediates.noin
                            dex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Binary/Runner
                        ld: in
/Users/keithblack/GitHub/flutter_application_1/ios/Pods/mobile-ffmpeg-audio/lame.framework/lame(VbrTag.o),
                        building for iOS Simulator, but linking in object file built for iOS, file
                        '/Users/keithblack/GitHub/flutter_application_1/ios/Pods/mobile-ffmpeg-audio/lame.framework/lame'
for architecture
                        arm64
                        clang: error: linker command failed with exit code 1 (use -v to see invocation)
                    
                    
[+4734 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone 12 Pro.
[   +5 ms] "flutter run" took 49,727ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +63 ms] ensureAnalyticsSent: 61ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
[flutter_sound_example_build_log.txt](https://github.com/Canardoux/tau/files/7247139/flutter_sound_example_build_log.txt)

**Comment by Larpoux** [comment]
Do you run on x86 or Apple Silicon M1 ?

**Comment by tkeithblack** [comment]
Mac Book Pro - Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz, not the M1.

**Comment by Larpoux** [comment]
>                         building for iOS Simulator, but linking in object file built for iOS, file
>                         '/Users/keithblack/GitHub/flutter_application_1/ios/Pods/mobile-ffmpeg-audio/lame.framework/lame'
>                         for architecture arm64

I think that there is a problem with Mobile FFmpeg and the architecture x86/arm64.
Do you use Flutter FFmpeg yourself ?
Did you add a dependency to Mobile FFmpeg in your Podifle ?

Perhaps you can try to build your app with flutter_ffmpeg LITE, just to see if the problem is still there or disappears.

**Comment by tkeithblack** [comment]
I tried the LITE version but it did not work, there were other errors with that one.

The reason I created a brand new project is to make sure another packages in my app were not causing the problem. This was a brand new default counter app with only the flutter_sound package. Nothing else. 

Keith

**Comment by Larpoux** [comment]
Weird
<img width="1417" alt="Screenshot 2021-09-29 at 00 28 28" src="https://user-images.githubusercontent.com/45900255/135174510-ab38c9d0-1b80-434a-a449-d45a664c1313.png">

I do not understand why it tries to lik-edit with a version of Mobile-FFmpeg for arm64 iOS.
There is something wrong on your dev. machine, but I do not see where.
Sorry.

**Comment by Larpoux** [comment]
Perhaps a problem of compatibility between CocoaPods and Flutter.
But I guess that if your CocoaPods is not the good version, Flutter would have tell it.

Sorry again. I do not see the reason of your problem.

**Comment by tkeithblack** [comment]
Thanks for your assistance, you are correct that my machine does not have the iOS-arem64 directories.

BTW, In trying to fix this I upgraded to CocoaPods 1.11.2.

![image](https://user-images.githubusercontent.com/16345467/135175540-873c0a6d-f993-4790-adf8-64278183d3e1.png)

**Comment by tkeithblack** [comment]
Today I tried the following to force a complete rebuilding the Pods directory (which includes the **mobile-ffmpeg-audio** folder):

deleted the **ios/Pods** directory
**pod cache clean --all**
**flutter clean**
**flutter pub get** 
**pod deintegrate**
**pod install**  

I was hoping this would fix things. Unfortunately it did not. I still have only the **info.plist** and **lame** documents in the **lame.framework** directory, no **arm64** directories. And I still cannot run my app on the iOS simulator, only a physical device. BTW, I am able to run on the Android simulator.

Does anyone have any idea how to resolve this?

Thanks for your help.

**Comment by jomonylw** [comment]
I also met the same issue after upgrading to flutter 2.5

**Comment by Larpoux** [comment]
It is possible that there is something bad on MobileFFmpeg with flutter 2.5

> I still cannot run my app on the iOS simulator

It is not easy for me to debug that, because I work on a Macintosh with an Apple Silicon M1 proc.
MobileFFmpeg does not like the M1, and cannot run on an iOS emulator.

The big problems are : 
- I really want a FULL version of Flutter Sound/Tau Sound with FFmpeg support : I have several plans to use FFmpeg on new features.
- MobileFFmpeg is not supported anymore

I am currently working on a V9 version of Tau Sound. If I have time (but I doubt it), I will try to fork MobileFFmpeg and try to fix those issues. Until that, perhaps you can use the LITE flavor of Flutter Sound

**Comment by tkeithblack** [comment]
I appreciate the help. I'm surprised there are not more encountering this issue. Like I said in the first message, rolling back to a previous version of Flutter got rid of the problem.

**Comment by Larpoux** [comment]
Hi,

Today, I was able to get a hand on a Macintosh x86.
Flutter 2.6.
I was able to build and run the Demo App, **without any issue**.

So, your problem is less simple than just a problem of incompatibility between flutter 2.5 and Flutter Sound.

**Comment by Larpoux** [comment]
Mobile FFmpeg is dead and not supported anymore.
People of this project are busy working on a new library : FFmpeg-Kit.

This library is supposed to be released during the incoming week.
I will try to migrate to this library, and we will see if the situation is better.

**Comment by lekeCoder** [comment]
l had the same issue and when l switch the `channel` to `beta` and upgraded, worked fine. So you may need to switch channel to beta
