### ISSUE TITLE
[BUG]: Context.startForegroundService() did not then call Service.startForeground():

### ISSUE THREAD

**Issue by sallypeters** [Canardoux/flutter_sound#780]
## Flutter Sound Version : 
- LITE

- **Important**: Result of the command :

 ```flutter pub deps | grep flutter_sound```
```

|-- flutter_sound_lite 8.4.1
|   |-- flutter_sound_platform_interface 8.4.1
|   |-- flutter_sound_web 8.4.1
|   |   |-- flutter_sound_platform_interface...
```
----------------------------------------------------------

## Severity

-Crashes with the error : 

```
/AndroidRuntime(31243): Shutting down VM
E/AndroidRuntime(31243): FATAL EXCEPTION: main
E/AndroidRuntime(31243): Process: com.ryanheise.audioserviceexample, PID: 31243
E/AndroidRuntime(31243): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7519a88 u0 com.ryanheise.audioserviceexample/com.dooboolab.TauEngine.FlautoBackgroundAudioService}
E/AndroidRuntime(31243): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
E/AndroidRuntime(31243): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(31243): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(31243): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(31243): 	at java.lang.reflect.Method.invoke(Native Method)

```

- Result is not what expected ?
Dont expect that just by adding the plugin **flutter sound lite** will crash the same audio service example

- Cannot build my App ?
Ok - can build but we get a warning on build : 

```
WARNING: [Processor] Library '/.gradle/caches/modules-2/files-2.1/com.github.canardoux/flutter_sound_core/8.4.1/df1da2efb4085098ab4cd8d45dc76626f0f6da3a/flutter_sound_core-8.4.1.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/arch/core/util/Function'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Callback'
```

- Minor issue ?
No - Major as adding Flutter_Sound_Lite increases RAM usage

--------------------------------------------------------

## Platforms you faced the error 

- Android
- Real device ? Yes , Samsung S10+

------------------------------------------------

**Describe the bug**
When you run the sample audio service here and then interface with the front screen controls (press pause, stop button etc a few times) - app crashes and we get the stack trace shown. 

**To Reproduce**
1. Fork or run the sample app of audio_service
https://github.com/ryanheise/audio_service/blob/07313c1aaee4551333bac3d8a9ab6198ac495b81/audio_service/example/lib/example_multiple_handlers.dart
2) Modify the pubspec.yaml to be : 
```
  path_provider: ^2.0.1
  audio_session: 0.1.6+1
  just_audio: 0.9.12
  flutter_tts: 3.2.2
  rxdart: ^0.27.2
  audio_service:  0.18.0
  flutter_sound_lite: 8.4.1
```

i.e we have just added **flutter_sound_lite 8.4.1**

3. Build and run your app for Android on Simulator or Live device.
4. On the main screen of your devices, press the PAUSE button a few times and then STOP -> Your app crashes.

----------------------------------------------

# Logs!!!!

We only include **Flutter_sound_lite** in pubspec.yaml. No class from **Flutter_Sound_Lite** is used or instantiated in this example.
-----------------------------------------------------------------

**Comment by Alvarocda** [comment]
Ok, I managed to reproduce this problem in an emulator.
I'm looking into what might be causing this.

**Comment by Larpoux** [comment]
@Alvarocda ,

Good morning my friend.
I suggest you do not work on this issue : 
I am going to look if using `audio_service` can be a viable solution for us.
You can do something else, like working on the τ Widgets. This is a good idea that you suggested.

@ryanheise ,
what do you think it would be better : 
- Make a dependency in τ Sound to `audio_service` and replace what we do with service by calls to the `audio_service` API (display on lock screen)
- Remove the the support of lock-screen display from our API, and let the App to write himself the glue between τ Sound and `audio_service`

My preference is to remove from τ Sound everything about Display on Lock Screen, but I am afraid that it would be not simple for the user : our App developers are not all programer experts, and they want something very simple.

**Comment by ryanheise** [comment]
Hi @Larpoux 

What I have done for just_audio is to make just_audio by itself only take care of playing audio, and then provided another package just_audio_background which optionally adds the background features (and internally depends on audio_service). That way the app developer can choose what to include.

just_audio_background is intended to be the easy option if the app developer doesn't want to do much setup. It is actually just a federated plugin implementation (and for the moment, still beta). Now another way I could have done it is to make just_audio_background a normal plugin that replaces just_audio providing a new frontend that mimics the same API as just_audio but internally depends on audio_service. Anyway, there are several options to address the "ease of use" factor, and then of course I also leave open the advanced option for people to use use audio_service directly with just_audio if they want full control over the notification and media session.

**Comment by Larpoux** [comment]
Yes. I was also thinking of something like that.
I think this is a good way to do things.

**Comment by sallypeters** [comment]
> Also I am not really happy that τ Sound depends on Flutter-FFmpeg (now FFmpeg-kit), to support stupid Apple things like the Apple CAF format (vs the regular OGG file format).

@Larpoux - I agree. Flutter Sound Lite is trying to be too many things to  too many people and as @ryanheise says 'trying to include everything including the kitchen sink'. I think Flutter sound lite should adopt a SBA (Service based architecture) where the architecture allows for services to be seamlessly plugged/glued together. 

If a user doesnt require LockScreen/Notification functionality then all well and good - if they do , then thats already been written and integrated into many apps (audio_service).

If only the recording elements of **FSL** is required then that could be packaged up into a new **FSR** (Flutter sound recorder) plugin - and potentially help with licensing (since fewer developers may have contributed to recording functionality as opposed to playback functionality within FSL).

Lastly , yes your comment here : 

> 
> Probably good if I propose another plugin simpler, and let τ Sound having only a limited responsibility.
> But at the end, τ Sound will just be a variant of just_audio 😆 !!!!

Is true & first principle SRP is part of the SOLID principles which every developer should actively enforce within their daily coding. However , I dont think its wrong for Flutter_Sound_lite to be another variant of Just_audio as it gives them choice plus **FSL** API may appeal to a different set of developers compared with **just_audio's API**.

In the end - if all audio plugins are designed so that they can all work seamlessly together without stepping on each others toes then developers can cherry pick the best parts of all of these plugins and use them in their apps.

**Comment by sallypeters** [comment]
@Larpoux Correct me if I'm wrong - but I think most app developer needs who rely on audio players like Flutter Sound will want a player that supports the very basic codecs that are supported on the two primary platforms and plays good quality audio without consuming large resources.

I also think that having a player that is rich on Audio features (Looping, Gapless playback, Clipping, Fast forward/rewind, play/pause/shuffle/buffering etc) is more important than catering for every conceivable codecs at the expense of creating a heavyweight client.  Sure, if a requirement needs multi codec support - then the users can bring in FFmpeg-kit themselves into their own app rather than making that a required dependency of Flutter Sound. Additionally you will reduce complexity and honour single chain of responsibility principle by making FS just concentrate on playing good quality audio.

I think a streamlined , easy API that doesnt need to re-invent the wheel (i.e if we need to play background audio we can latch onto audio_service which works and works well) - can coexist with other similar plugins is the way to go - making FS work with other great audio plugins can only make FS better and increase its adoption rate - thus I think for sure that  if τ Sound version builds upon this architecture then it will make the development process easier and allow τ Sound to be extended with minimal disruption and complexity to the wider developer base.

**Comment by sallypeters** [comment]
@Larpoux Depending on ones needs - having really intensive computation (encoding) is something that can easily be offloaded to a server process and then streamed to a client (iOS/Android client etc) when its complete. However, with the quality of chips in the latest handsets - I think client-side processing for encoding/decoding is a possibility ---- but something like this I would be inclined to offload it to a server if my use case didnt require always on connection ...

Lastly, regarding this issue that I raised (#780) - have you established whether **audio_service** will be a viable solution for **Flutter Sound** ?

**Comment by sallypeters** [comment]
@Larpoux Thats actually excellent. Perhaps you should also include MAUI (Apparently touted as a Flutter-killer) to that list ...

**Comment by yanivshaked** [comment]
Thanks. What about the FULL flavor of `τ` Sound 9.0? Will it be also compliant with `audio_service` and `audio_session`?

**Comment by Larpoux** [comment]
@yanivshaked ,
Actually, this is not clear what we must do with the FULL flavor.
I would like very much to simplify τ and remove all the code about `StartPlayerFromTrack()' and `nowPlaying()` : less code => less bugs, less documentation, and less work to maintain.
But I have not yet looked deeply into audio_service. My first impression is that the audio_service API is complicated for a casual τ user.
I talked with the main audio_service maintainer, and he told me that his own choice was to support two plugins : 
- A very simple one without anything with lock screen, services, ... : this is `Just Audio`
- A very high level plugin which internally uses `Just Audio` and `Audio Service`

We (I) actually maintain two flavor of  τ sound.
This is not possible to maintain 4 different plugins.

We (I) have not yet decided what we must do for the FULL flavor : 
- Remove everything about `nowPlaying()` and `startPlayerFromTrack()` from the API
- Keep the actual code
- Support `nowPlaying()` and `startPlayerFromTrack()`, but internally use `Audio Service` instead of our own code

What do you think?

**Comment by yanivshaked** [comment]
Hi @Larpoux,

Indeed, maintaining two flavors of τ sound plugin is more than enough.

Regarding the FULL flavor of τ sound, keeping the actual code doesn't sound like a reasonable decision, since the collision with the `audio_service` plugin will remain in this case.
I believe that the first option of removing all service related APIs is the most reasonable solution. This way the programmer can enjoy the best of the τ sound plugin which using other plugins for lock screen/services.

**Comment by sallypeters** [comment]
@Larpoux 

> But I have not yet looked deeply into audio_service. My first impression is that the audio_service API is complicated for a casual τ user.

Yes, the audio_service sample code & API may prove somewhat daunting to the average Dart/Flutter user but it serves a purpose and serves that purpose well. I've used it seamlessly in a few non-trivial sound based apps with a mixture of Audio and TTS and the Audio Service is flawless in my uses-case.

I think its a win-win situation to offload the background service functionality that FSL handles onto audio_service - this would free up maintenance of that functionality within FSL and additionally allow FSL recording functionality to work in harmony with **audio_service**

I personally think  τ sound should be wrapped into multiple standalone plugins that each serves a specific purpose , potentially : 

- τ sound player
- τ sound recorder
- τ sound encoder
- τ sound ffmpeg

and a 

τ sound core

More importantly - what kind of license are you contemplating for τ sound that will allow 100% acceptance for both Play store and App Store ?

**Comment by Larpoux** [comment]
Thank you, guys and girls for your feedback.
I am very comfortable with the idea to remove `StartPlayerFromTrack()` from the code. This part of Flutter Sound was coded by @salvatore373 . He did a very good job, but unfortunately I do not master his code very well on Android.



> I personally think τ sound should be wrapped into multiple standalone plugins that each serves a specific purpose , potentially :
> 
> * τ sound player
> * τ sound recorder
> * τ sound encoder
> * τ sound ffmpeg

Sometimes I agree with you that there is no good reason to have both the player and the recorder in the same plugin.
But I want to say two things : 
- Flutter Sound was a plugin created by @hyochan . He insisted very much that the Flutter Sound purpose was to have both the recorder and the player in the same plugin. I consider him as the boss, even if τ is now more my son. Until now, I have respected his mind.
- Actually we have two different things : 
   - The player
   - The recorder
Actually, the verb `startPlayerFromMic()` is in the "player" side. But there is no good reason that it must not be in the "recorder" side. Also, we can have something in the future which is neither a player nor a recorder, but just an Audio Engine able to run several nodes linked together. Those node can be various things like microphone, speaker, stream on internet, webrtc, dart streams, etc... I am not sure that we must publish a third plugin, because in my head, the recorder and the player are just simple examples of an implementation of this audio-engine

**Comment by Larpoux** [comment]
> More importantly - what kind of license are you contemplating for τ sound that will allow 100% acceptance for both Play store and App Store ?

When you publish an App on Google Play Store or Apple Appstore, you specify what is your license.
Apple and Google are agnostics about the license, even if most of the time publishers choose the regular/standard Apple and Google license. I believe that there is no problem with GPL.
Does anyone have something to say on this subject ?

**Comment by sallypeters** [comment]
@Larpoux 
Regarding the GPL licence, as I understand it - this is a grey legalese area within apps published on the app store utilising software packaged under GPL which is why app developers favour MIT, BSD or public domain type licenses. GPL basically means I do not own the software and any changes (and/or patches)  I make to the software must be published freely.

Additionally - If I understand GPL correctly - GPL requires you to grant all rights including source code, to everyone who receives any app that I publish on the app store and this includes fee based apps or non fee based apps. This would therefore imply that even if I didnt charge a fee for my app - everyone would be entitled to my source code. Thus it would appear that GPL isnt really suitable for releasing onto the app store as I dont really own anything produced under a GPL license. 

This has far reaching ramifications - if I use GPL licensed software where a number of developers have contributed (=> @hyochan) - then nothing stops those developers from complaining to Apple because they may feel I have used an unpublished feature within my app using their GPL software. Apple may or may not act on this. Worst case scenario - they pull my app from the app store.,

I think GPL potentially can be very restrictive and implications far-reaching.

Here is a good link 

[https://gustavopinto.medium.com/why-the-mit-license-is-much-more-used-then-gpl-3-2b3fa4271d6b](url)

**Comment by sallypeters** [comment]
@Larpoux 

> Flutter Sound was a plugin created by @hyochan . He insisted very much that the Flutter Sound purpose was to have both the recorder and the player in the same plugin. I consider him as the boss, even if τ is now more my son. Until now, I have respected his mind.

I've used Flutter Sound for approx 3 years and was quite vocal with hyochan during the early years of FS (In those days there was severe issues regarding very large file sizes created when recording just a simple 10-sec AAC recording and hyochan was initially reluctant to address this - overtime though, he saw sense and the issues were resolved. 

I think regardless of what one's vision was - the only think constant in life is **change** and sometimes things need to change if it means **something better** can be built....

**Comment by Larpoux** [comment]
@sallypeters ,
Hi Sally,
most I think to your post, most I think that you are right : Flutter Sound (Tau Sound) is already too complicated and it would be a mistake to continue to add new things not directly linked with the actual functionalities.

It makes sense to create a new plugin to play audio-graphs, instead of adding this stuff inside Tau Sound.
Also, actually the native implementations on iOS and Android implements two different code for playbacks : 
- Some legacy code use the native Sound Media Player
- Some different code to play or record Dart Streams

I would be very happy to split this code into two different plugins.

But the most important, now, is not to change the architecture. What is urgent is to publish a final 9.0 release.
Several things must be done for 9.0 : 
- Remove the Session concept from the API
- Remove the "NowPlaying" stuff (audio_service) from the API.
- Write some examples to show how to use `audio_service` and `audio_session`
- **AND WRITE THE NEW API DOCUMENTATION**

I would be very happy if we can release 9.0 soon. Unfortunately I am very busy and slow in my progression.

**Comment by alexda12** [comment]
@sallypeters @Larpoux 
I also have this issue - I cannot use just_audio with Flutter Sound Lite because of the issue raised here.

@Larpoux Do you have any immediate plans to remove the service code in your manifest so that Flutter Sound Lite can co-exist with Just Audio ?

**Comment by Larpoux** [comment]
Hi Guys and Girls.

I had stopped working on Tau for several weeks.
But I just decide now to try to terminate Tau 9.0. Probably in a few weeks ...

But it is very important that other developers will work on Tau soon.
I will not be available for tau in the long run.

**Comment by alexda12** [comment]
@Larpoux Just to confirm -  Does this mean that Flutter Sound and TAU will now been abandoned and discontinued ?
