### ISSUE TITLE
[BUG]: FlautoBackgroundAudioService requires explicit value for android:exported

### ISSUE THREAD

**Issue by marcoberetta96** [Canardoux/flutter_sound#789]
## Flutter Sound Version : 
8.4.1+1

- Result of the command : ```flutter pub deps | grep flutter_sound```
```
|-- flutter_sound 8.4.1+1
|   |-- flutter_sound_platform_interface 8.4.1
|   |-- flutter_sound_web 8.4.1
|   |   |-- flutter_sound_platform_interface...
```

## Severity
App does not install on Android 12.

--------------------------------------------------------

## Platforms you faced the error 
Android 12 only.

------------------------------------------------

# Logs
```

[ +149 ms] Installing APK.
[   +3 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /mnt/DATA/Utils/Sdk/platform-tools/adb -s 948AY0KK49 install -t -r /home/marco/my_app/build/app/outputs/flutter-apk/app.apk
[+12935 ms] Performing Streamed Install

                     adb: failed to install /home/marco/my_app/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI:
                     /data/app/vmdl99420938.tmp/base.apk (at Binary XML file line #548): com.dooboolab.TauEngine.FlautoBackgroundAudioService: Targeting S+ (version 31 and above) requires that an explicit value
                     for android:exported be defined when intent filters are present]
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 12.9s)
[   +2 ms] Error: ADB exited with exit code 1
[        ] Performing Streamed Install
           
           adb: failed to install /home/marco/my_app/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI:
/data/app/vmdl99420938.tmp/base.apk (at
           **Binary XML file line #548): com.dooboolab.TauEngine.FlautoBackgroundAudioService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent
filters are
           present]**
[        ] Warning: Failed to install APK.
[        ] Error launching application on Pixel 3a.
[  +28 ms] "flutter run" took 127,013ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +116 ms] ensureAnalyticsSent: 114ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

This is probably what should be done (part of the log): "Binary XML file line # 548): com.dooboolab.TauEngine.FlautoBackgroundAudioService: Targeting S+ (version 31 and above) **requires that an explicit value for android:exported** be defined when intent filters are present]"

**Comment by marcoberetta96** [comment]
I did not understand how to make a pull request for this, so I write down here the solution, or at least I think so :)

The file `tau_native/android/src/main/AndroidManifest.xml` from `https://github.com/canardoux/tau.git` should be done like this:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="xyz.canardoux.TauNative">

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <application>
	<receiver android:name="androidx.media.session.MediaButtonReceiver"
	android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
                <action android:name="android.media.AUDIO_BECOMING_NOISY" />
            </intent-filter>
        </receiver>

        <service android:name=".FlautoBackgroundAudioService"
        android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
                <action android:name="android.media.AUDIO_BECOMING_NOISY" />
                <action android:name="android.media.browse.FlautoMediaBrowserService" />
            </intent-filter>
        </service>
    </application>
</manifest>
```

Basically, the line `android:exported="true"` has to be added to the receiver and the service.

**Comment by Larpoux** [comment]
Hi Marco,

Thank you for your fix. I am going to apply it on the `flutter_sound V8.4` master branch.
For `tau_sound V9.0`, we are considering to remove all the code about Android Audio Service. [See here #780](https://github.com/Canardoux/flutter_sound/issues/780).

Thank you for your contribution.

**Comment by Larpoux** [comment]
Hi Marco.
Flutter Sound 8.4.2 is published with your fix.
Thank you again for your contribution

**Comment by marcoberetta96** [comment]
Nice! Thanks to you!
