### ISSUE TITLE
[HELP]: E/AudioRecord(13891): start(317): status -38

### ISSUE THREAD

**Issue by rranjan007** [Canardoux/flutter_sound#795]
## For example the _Element_ τ room ?

------------

I need Help for :

Getting this error 

I/flutter (13891): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (13891): │ #0   FlutterSoundRecorder._startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:659:13)
I/flutter (13891): │ #1   FlutterSoundRecorder.startRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:637:13)
I/flutter (13891): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (13891): │ 🐛 FS:---> _startRecorder.
I/flutter (13891): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/AudioRecord(13891): start(317): status -38
I/System.out(13891): ---> writeAudioDataToFile
I/System.out(13891): <--- writeAudioDataToFile

===============================================

The main error line is this

`E/AudioRecord(13891): start(317): status -38`

- Using the API ?
   startRecorder()
- Generate an iOS or Android App ?
   Generate in Android
   
`await _mRecorder.startRecorder(toFile: _mPath, sampleRate: 44100, codec: Codec.pcm16WAV, bitRate: 0);`

-------------------------------------
## Here is my question :

I get this error randomly when I call the startRecorder command as above in android. I have called the openAudioSession before calling the startRecorder method. 

- I am not sure why i get this error randomly
- When i get this error, i don't get any callback to handle this in my code.

@Larpoux , can you please help me with this. Thanks.

**Comment by rranjan007** [comment]
Any update here guys ?

**Comment by mhstoller** [comment]
Share your full code. Also not sure why you set bitrate to 0.
