### ISSUE TITLE
[HELP]: Cannot Record Audio

### ISSUE THREAD

**Issue by vishnuagbly** [Canardoux/flutter_sound#810]
------------

I need Help for :

- Using the API ?

-------------------------------------
## Here is my question :
I was trying to use SoundRecorderUI but found myself unable to, as it does not work, keeps stopping.

Following is code:
```
Directory tempDir = await getTemporaryDirectory();
String outputFile = '${tempDir.path}/myFile.pcm';
soundTrack = Track(trackPath: outputFile);
```
Code for building the Widget.
```
SoundRecorderUI(
                      soundTrack!,
                      requestPermissions: requestSoundPermissions,
                      onStopped: (audio) {
                        setState(() => recordedTrack = audio.track);
                      },
                    ),
```
Code for requestSoundPermissions(while I don't believe that problem lies here):
```
Future<bool> requestSoundPermissions(
      BuildContext context, Track track) async {
    final micPermission = await Permission.microphone.status;
    if (micPermission.isDenied) {
      final status = await Permission.microphone.request();
      if (status.isDenied) return false;
    }
    final storagePermission = await Permission.storage.status;
    if (storagePermission.isDenied) {
      final status = await Permission.storage.request();
      if (status.isDenied) return false;
    }
    return true;
  }
```

Following are the logs on just creating the SoundRecorderUI:
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.764 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:155:13)
2021-12-15 18:29:06.764 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   SoundRecorderUIState.initState (package:flutter_sound/public/ui/sound_recorder_ui.dart:232:17)
2021-12-15 18:29:06.764 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.764 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 ctor: FlutterSoundRecorder()
2021-12-15 18:29:06.764 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.767 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.767 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:393:13)
2021-12-15 18:29:06.767 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   SoundRecorderUIState.initState (package:flutter_sound/public/ui/sound_recorder_ui.dart:234:10)
2021-12-15 18:29:06.767 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.767 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 FS:---> openAudioSession 
2021-12-15 18:29:06.767 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.771 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.771 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder._openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:413:13)
2021-12-15 18:29:06.771 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   FlutterSoundRecorder.openAudioSession.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:395:17)
2021-12-15 18:29:06.772 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.772 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 ---> openAudioSession
2021-12-15 18:29:06.772 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.775 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.775 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder._openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:428:17)
2021-12-15 18:29:06.775 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   FlutterSoundRecorder.openAudioSession.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:395:17)
2021-12-15 18:29:06.775 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.775 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 Resetting flutter_sound Recorder Plugin
2021-12-15 18:29:06.775 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.780 15877-15877/com.example.flutter_dristhi E/MethodChannel#com.dooboolab.flutter_sound_recorder: Failed to handle method call
    java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
        at com.dooboolab.fluttersound.FlutterSoundManager.resetPlugin(FlutterSoundManager.java:88)
        at com.dooboolab.fluttersound.FlutterSoundRecorderManager.onMethodCall(FlutterSoundRecorderManager.java:70)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-15 18:29:06.780 15877-15877/com.example.flutter_dristhi E/DartMessenger: Uncaught exception in binary message listener
    java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-15 18:29:06.832 1405-7298/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10557/15877 clientId=android.media.AudioManager@c58a990 callingPack=com.example.flutter_dristhi req=3 flags=0x0 sdk=30
2021-12-15 18:29:06.865 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.865 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.openRecorderCompleted (package:flutter_sound/public/flutter_sound_recorder.dart:186:13)
2021-12-15 18:29:06.865 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:98:22)
2021-12-15 18:29:06.865 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.865 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 ---> openRecorderCompleted: true
2021-12-15 18:29:06.865 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.866 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.866 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.openRecorderCompleted (package:flutter_sound/public/flutter_sound_recorder.dart:197:13)
2021-12-15 18:29:06.866 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:98:22)
2021-12-15 18:29:06.866 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.866 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 <--- openRecorderCompleted: true
2021-12-15 18:29:06.866 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder._openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:449:13)
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   <asynchronous suspension>
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 <--- openAudioSession
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:403:13)
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   <asynchronous suspension>
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:29:06.868 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 FS:<--- openAudioSession 
2021-12-15 18:29:06.869 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Following are the logs on clicking the record button in the recorder UI.
```
20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.324 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.setSubscriptionDuration (package:flutter_sound/public/flutter_sound_recorder.dart:561:13)
2021-12-15 18:31:45.324 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   SoundRecorderUIState._onRecord (package:flutter_sound/public/ui/sound_recorder_ui.dart:420:24)
2021-12-15 18:31:45.324 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:31:45.324 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 FS:---> setSubscriptionDuration 
2021-12-15 18:31:45.324 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.329 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.329 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.setSubscriptionDuration (package:flutter_sound/public/flutter_sound_recorder.dart:568:13)
2021-12-15 18:31:45.329 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   <asynchronous suspension>
2021-12-15 18:31:45.329 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:31:45.329 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 FS:<--- setSubscriptionDuration 
2021-12-15 18:31:45.329 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.332 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.332 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder.startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:635:13)
2021-12-15 18:31:45.332 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   SoundRecorderUIState._onRecord (package:flutter_sound/public/ui/sound_recorder_ui.dart:421:24)
2021-12-15 18:31:45.332 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:31:45.332 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 FS:---> startRecorder 
2021-12-15 18:31:45.333 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.335 15877-20904/com.example.flutter_dristhi I/flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.335 15877-20904/com.example.flutter_dristhi I/flutter: │ #0   FlutterSoundRecorder._startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:659:13)
2021-12-15 18:31:45.335 15877-20904/com.example.flutter_dristhi I/flutter: │ #1   FlutterSoundRecorder.startRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:637:13)
2021-12-15 18:31:45.335 15877-20904/com.example.flutter_dristhi I/flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-12-15 18:31:45.335 15877-20904/com.example.flutter_dristhi I/flutter: │ 🐛 FS:---> _startRecorder.
2021-12-15 18:31:45.335 15877-20904/com.example.flutter_dristhi I/flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-15 18:31:45.350 15877-15877/com.example.flutter_dristhi E/IAudioFlinger: createRecord returned error -1
2021-12-15 18:31:45.350 15877-15877/com.example.flutter_dristhi E/AudioRecord: createRecord_l(1818586734): AudioFlinger could not create record track, status: -1
2021-12-15 18:31:45.350 15877-15877/com.example.flutter_dristhi E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
2021-12-15 18:31:45.350 15877-15877/com.example.flutter_dristhi E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2021-12-15 18:31:45.356 15877-20904/com.example.flutter_dristhi E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(startRecorder, startRecorder, Failure to start recorder, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      FlutterSoundRecorder._startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:732:7)
    <asynchronous suspension>
    #3      FlutterSoundRecorder.startRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:637:7)
    <asynchronous suspension>
    #4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
    <asynchronous suspension>
    #5      FlutterSoundRecorder.startRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:636:5)
    <asynchronous suspension>
    #6      SoundRecorderUIState._onRecord (package:flutter_sound/public/ui/sound_recorder_ui.dart:421:7)
    <asynchronous suspension>

```

**Comment by EclipseAndrey** [comment]
same problem

**Comment by alexda12** [comment]
@EclipseAndrey @vishnuagbly 

It would appear that this plugin is now being retired so time to find something better.

See here :-  #780

**Comment by shinewanna** [comment]
After digging, add log level to nothing to avoid that logs, like below.

import 'package:logger/src/logger.dart';

_audioPlayer = FlutterSoundPlayer(logLevel: Level.nothing);

**Comment by 191278** [comment]
@Larpoux can you please help having similar issues like this, using 
flutter_sound: ^9.1.9
audio_session: ^0.1.6+1
