### ISSUE TITLE
[HELP]:

### ISSUE THREAD

**Issue by Seferi** [Canardoux/flutter_sound#836]
I need Help for :

- Using the API ?

-------------------------------------
## Here is my question :

I have this part of the code where I expect the stop icon to change to play icon when the player finished playing the file.
`
IconButton(
                                      onPressed: () async {
                                        if (_isPlaying) {
                                          _isPlaying = false;
                                          setState(() {});
                                          await audioPlayer.stopPlaying();
                                        } else {
                                          _isPlaying = true;
                                          _fileNamePlaying = entry.fileName;
                                          setState(() {});
                                          await audioPlayer
                                              .play(entry.fileName);
                                          _isPlaying = false;
                                          setState(() {});
                                        }
                                      },
                                      icon: Icon(
                                          _isPlaying &&
                                                  _fileNamePlaying ==
                                                      entry.fileName
                                              ? Icons.stop
                                              : Icons.arrow_right,
                                          size: 30)),
`

For some reason await audioPlayer.play(entry.fileName); doesn't wait and executes the rest of the code thus the play icon changes to to stop and play immediately. I appreciate if someone could help. Thanks.

**Comment by Larpoux** [comment]
What is `audioPlayer`? Is it an instance of another plugin than Flutter Sound?
If yes, we know some incompatibilities between Flutter Sound and other plugins in Flutter Sound v8.x

You should try v9.x. We changed several things for better compatibility

**Comment by Seferi** [comment]
audioPlayer is the FlutterSoundPlayer() from flutter_sound. I'm using the latest version 9.1.2. Everything works perfectly. Its just the await FlutterSoundPlayer().startPlayer() doesn't await...

**Comment by Seferi** [comment]
Am I supposed to use setSubscriptionDuration and listen to that and await for it ? Is that how its suppose to work ?

**Comment by Larpoux** [comment]
No. SetSubscriptionDuration does not have any impact on the startPlayer completion.

Can we have your logs?

**Comment by Seferi** [comment]
```
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   new FlutterSoundPlayer (package:flutter_sound/public/flutter_sound_player.dart:130:13)
I/flutter ( 9877): │ #1   SoundApi.initPlayerOnly (package:practice_tools/data/api/sound_api.dart:53:20)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 ctor: FlutterSoundPlayer()
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:500:13)
I/flutter ( 9877): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:494:17)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:---> openAudioSession
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:513:15)
I/flutter ( 9877): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:494:17)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 Resetting flutter_sound Player Plugin
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.openPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:192:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:96:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 ---> openPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.openPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:207:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:96:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 <--- openPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:533:13)
I/flutter ( 9877): │ #1   <asynchronous suspension>
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:<--- openAudioSession
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:770:13)
I/flutter ( 9877): │ #1   FlutterSoundPlayer.startPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:750:17)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:---> startPlayer 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._stop (package:flutter_sound/public/flutter_sound_player.dart:1090:13)
I/flutter ( 9877): │ #1   FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:797:11)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:---> _stop 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:294:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:113:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 ---> stopPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:309:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:113:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 <--- stopPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._stop (package:flutter_sound/public/flutter_sound_player.dart:1117:13)
I/flutter ( 9877): │ #1   <asynchronous suspension>
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:<--- _stop 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:822:13)
I/flutter ( 9877): │ #1   <asynchronous suspension>
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:<--- startPlayer 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:358:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 mediaPlayer prepared and started
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.startPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:275:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:106:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 ---> startPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.startPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:287:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:106:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 <--- startPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:358:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 Playback completed.
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
V/MediaPlayer( 9877): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9877): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 9877): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9877): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.audioPlayerFinished (package:flutter_sound/public/flutter_sound_player.dart:174:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:82:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:---> audioPlayerFinished
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._stopPlayer (package:flutter_sound/public/flutter_sound_player.dart:1071:13)
I/flutter ( 9877): │ #1   FlutterSoundPlayer.stopPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:1066:13)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:---> _stopPlayer 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._stop (package:flutter_sound/public/flutter_sound_player.dart:1090:13)
I/flutter ( 9877): │ #1   FlutterSoundPlayer._stopPlayer (package:flutter_sound/public/flutter_sound_player.dart:1082:13)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:---> _stop 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:294:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:113:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 ---> stopPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.stopPlayerCompleted (package:flutter_sound/public/flutter_sound_player.dart:309:13)
I/flutter ( 9877): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:113:19)
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 <--- stopPlayerCompleted: true
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._stop (package:flutter_sound/public/flutter_sound_player.dart:1117:13)
I/flutter ( 9877): │ #1   <asynchronous suspension>
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:<--- _stop 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer._stopPlayer (package:flutter_sound/public/flutter_sound_player.dart:1086:13)
I/flutter ( 9877): │ #1   <asynchronous suspension>
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:<--- stopPlayer 
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 9877): │ #0   FlutterSoundPlayer.audioPlayerFinished (package:flutter_sound/public/flutter_sound_player.dart:185:13)
I/flutter ( 9877): │ #1   <asynchronous suspension>
I/flutter ( 9877): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9877): │ 🐛 FS:<--- audioPlayerFinished
I/flutter ( 9877): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by Seferi** [comment]
If I add await Future.delayed with the duration of the audioFile right under the await audioPlayer.play(entry.fileName); then it works and setState is executed after the await. I just don't understand why await audioPlayer.play() doesn't await the same amount..

**Comment by Seferi** [comment]
> Your logs seem correct. I think that the problem is in your dart code. I do not understand what you are trying to do. I am surprised for example that you change the state of your player and do a setState before you await startRecorder and not after.
> 
> Also you must understand that startPlayer returns when the playback is started and not when the playback is finished. If you need to know when the playback is finished you must use the 'whenFinished' call back I

You mean whenCompleted() ? I tried that as well. Didn't work..

**Comment by Seferi** [comment]
The code after await _audioPlayer!.startPlayer(); just executed immediately instead of waiting...

**Comment by Larpoux** [comment]
Yes, it returns immediately because the playback starts very quickly.
It does not mean that the playback is finished. It is just started

**Comment by Seferi** [comment]
For example, I just tried this:
await audioPlayer .play(entry.fileName).whenComplete(() { print("FINISHED PLAYING");});
it prints immediately FINISHED PLAYING instead of waiting for the method to finish...

**Comment by Larpoux** [comment]
No, you must use
```dart
myPlayer.startPlayer(..., whenFinished: () {do something},) ;
```
whenFinished is an optional parameter for startPlayer

**Comment by Seferi** [comment]
Thanks for the clarification mate. 
Here is the method I'm calling to play:
```Future play(String fileName, Function setState) async {
    if (_isSoundApiInitialized || _isAudioPlayerInitialized) {
      await _audioPlayer!.startPlayer(
        fromURI: pathToSaveAudio + fileName + ".mp4",
        codec: _codec, whenFinished: setState(),
      );
    } else {
      return;
    }
  }
```
And here is how I'm calling it from my UI : 
```
await audioPlayer.play(entry.fileName, 
() {
_isPlaying = false;
print("FINISHED PLAYING!"); 
setState(() {});
});
```
I'm just passing the function as a parameter in the startPlayer. It still doesn't wait to call the function...

**Comment by Seferi** [comment]
Can you please do me a favor and check if the whenFinished works properly for you ? That it executes after the playback ? I'd very much appreciate. Thanks in advance.

**Comment by Larpoux** [comment]
Just change
```dart
whenFinished: setState()
```
By
```dart
whenFinished: setState, 
```

**Comment by Larpoux** [comment]
But you should name your function something else than `setState`.
This name is really confusing

**Comment by Seferi** [comment]
> Just change
> 
> ```dart
> whenFinished: setState()
> ```
> 
> By
> 
> ```dart
> whenFinished: setState, 
> ```

I tried this already. The argument type 'Function' can't be assigned to the parameter type 'void Function()?'.

**Comment by Larpoux** [comment]
You must declare your formal parameter as a TWhenFinished. And not Function

**Comment by Seferi** [comment]
> But you should name your function something else than `setState`.
> This name is really confusing

You are right with the naming, i'm just trying to get it to work first and then I'll think about the naming and other things..

**Comment by Larpoux** [comment]
Change the type of your formal parameter

**Comment by Larpoux** [comment]
😄
You are completely lost.
Your code is completely erroneous.

**Comment by Seferi** [comment]
The code is not complicated actually mate. I just wanna change one bool after the player finishes and the setState... That's all... How would you write this then ?

**Comment by Larpoux** [comment]
```dart
Future play(String fileName, TWhenFinished setState) async {
    if (_isSoundApiInitialized || _isAudioPlayerInitialized) {
      await _audioPlayer!.startPlayer(
        fromURI: pathToSaveAudio + fileName + ".mp4",
        codec: _codec, whenFinished: setState,
      );
    } else {
      return;
    }
  }
```

```dart
await audioPlayer.play(entry.fileName, 
() {
_isPlaying = false;
print("FINISHED PLAYING!"); 
setState(() {});
});
```

or Maybe (I am not sure) : 
```
await audioPlayer.play(entry.fileName, 
void () {
_isPlaying = false;
print("FINISHED PLAYING!"); 
setState(() {});
});
```

**Comment by Seferi** [comment]
Well this is exactly what I did.. And it does not work...

**Comment by Larpoux** [comment]
It compiles ?

**Comment by Seferi** [comment]
Wait a sec, I have overseen something.. You changed the parameter in play method as well..

**Comment by Seferi** [comment]
Now that worked... I'd really suggest adding this parameter type info to the docs as well. Or on android studio when hovered over the method... It's very confusing. 
Now how can i buy you a beer mate ? Donate to the project ?

**Comment by Larpoux** [comment]
😄 

Just click on the "likes" button on top of pub.dev.

I am really happy when people are pleased by my work.
Take care.
