### ISSUE TITLE
[HELP]:On android, startPlayer in the background, when app is not in focus, after some time, it will die and give the following error.

### ISSUE THREAD

**Issue by changcw83** [Canardoux/flutter_sound#851]
E/flutter (15854): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, startPlayer() error, null)
E/flutter (15854): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (15854): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854): #2      MethodChannelFlutterSoundPlayer.invokeMethod (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:157:12)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854): #3      FlutterSoundPlayer._startPlayer (package:flutter_sound/public/flutter_sound_player.dart:810:19)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854): #4      FlutterSoundPlayer.startPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:750:11)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854): #6      FlutterSoundPlayer.startPlayer (package:flutter_sound/public/flutter_sound_player.dart:749:5)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854): #7      _ShowprayersTabState.playdmk (package:prayers_deck/tabs/showprayers_tab.dart:136:5)
E/flutter (15854): <asynchronous suspension>
E/flutter (15854):

**Comment by Larpoux** [comment]
Could I have the logs, please?

**Comment by changcw83** [comment]
How do I get the log? I only extracted the relevant error message from the
log
