### ISSUE TITLE
thats what i get when i call openAudioSession()i() [BUG]:

### ISSUE THREAD

**Issue by jack84156** [Canardoux/flutter_sound#873]
I/flutter (14550): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): │ #0   new FlutterSoundPlayer (package:flutter_sound_lite/public/flutter_sound_player.dart:213:13)
I/flutter (14550): │ #1   Test2State.initState (package:whosaround/test2.dart:33:12)
I/flutter (14550): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14550): │ 🐛 ctor: FlutterSoundPlayer()
I/flutter (14550): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound_lite/public/flutter_sound_player.dart:671:13)
I/flutter (14550): │ #1   FlutterSoundPlayer.openAudioSession.<anonymous closure> (package:flutter_sound_lite/public/flutter_sound_player.dart:651:17)
I/flutter (14550): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14550): │ 🐛 FS:---> openAudioSession
I/flutter (14550): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound_lite/public/flutter_sound_player.dart:686:15)
I/flutter (14550): │ #1   FlutterSoundPlayer.openAudioSession.<anonymous closure> (package:flutter_sound_lite/public/flutter_sound_player.dart:651:17)
I/flutter (14550): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14550): │ 🐛 Resetting flutter_sound Player Plugin
I/flutter (14550): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
V/AudioManager(14550): stopBluetoothSco...
V/AudioManager(14550): setBluetoothScoOn  on: false
I/AudioManager(14550): setBluetoothScoOn on:false
V/AudioManager(14550): setSpeakerphoneOn  on: true
I/AudioManager(14550): setSpeakerphoneOn on:true
V/AudioManager(14550): registerAudioFocusListener...
V/AudioManager(14550): setSpeakerphoneOn  on: true
I/AudioManager(14550): setSpeakerphoneOn on:true
V/AudioManager(14550): setBluetoothScoOn  on: false
I/AudioManager(14550): setBluetoothScoOn on:false
V/AudioManager(14550): stopBluetoothSco...
V/AudioManager(14550): setMode  mode: 0
I/AudioManager(14550): setMode mode:0
I/flutter (14550): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): │ #0   FlutterSoundPlayer.openPlayerCompleted (package:flutter_sound_lite/public/flutter_sound_player.dart:334:13)
I/flutter (14550): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:120:19)
I/flutter (14550): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14550): │ 🐛 ---> openPlayerCompleted: true
I/flutter (14550): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): │ #0   FlutterSoundPlayer.openPlayerCompleted (package:flutter_sound_lite/public/flutter_sound_player.dart:349:13)
I/flutter (14550): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:120:19)
I/flutter (14550): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14550): │ 🐛 <--- openPlayerCompleted: true
I/flutter (14550): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14550): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound_lite/public/flutter_sound_player.dart:710:13)
I/flutter (14550): │ #1   <asynchronous suspension>
I/flutter (14550): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14550): │ 🐛 FS:<--- openAudioSession
I/flutter (14550): └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by Larpoux** [comment]
I do not understand what is your problem.
OpenAudioSession() seems ok.
Everything seems good

**Comment by Larpoux** [comment]
Note: OpenAudioSession() is deprecated in 9.x and is replaced by openPlayer() and openRecorder()

**Comment by BirgitPohl** [comment]
Dear @Larpoux I just want to mention that I have found some documentation [here and there](https://flutter-sound.canardoux.xyz/guides_getting_started.html) that is still recommending to choose the deprecated methods.
