### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by akhlaqshah** [Canardoux/flutter_sound#883]
## Flutter Sound Version : 

- **FULL** or **LITE** flavor ?
- Full

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

## Severity

- Crash ?

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 
- Flutter Web 

------------------------------------------------

**Describe the bug**
I'm playing audio files and changing on a button click, the player show this error at random files, and all files are mp3 audio format

**To Reproduce**
1. Playing MP3 audio files one by one and stops playing at random places
----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug).
To activate the logs, you must instantiate your modules with the Log Level set to `Level.debug` :
```
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
│ #1   packages/flutter_sound/public/flutter_sound_player.dart 299:15                                                                 stopPlayerCompleted
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 <--- stopPlayerCompleted: true
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
│ #1   packages/flutter_sound/public/flutter_sound_player.dart 360:13                                                                 log
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 onload
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
TypeError: Cannot read properties of null (reading 'play')
    at Howl.onload (http://localhost:54332/assets/packages/flutter_sound_web/src/flutter_sound_player.js:86:14)
    at Howl.<anonymous> (http://localhost:54332/assets/packages/flutter_sound_web/howler/howler.js:1885:16)
```
See [this](https://tau.canardoux.xyz/logger.html)

-----------------------------------------------------------------

**Comment by akhlaqshah** [comment]
The issue was in my data source, I was providing null Uint8List
