### ISSUE TITLE
[BUG]: iOS - Multiple Flutter Sound Player instances - starting player crash

### ISSUE THREAD

**Issue by Vedranivic** [Canardoux/flutter_sound#900]
## Flutter Sound Version : 

- **FULL**
- Result of the command : ```flutter pub deps | grep flutter_sound```
|-- flutter_sound 9.2.13
|   |-- flutter_sound_platform_interface 9.2.13
|   |-- flutter_sound_web 9.2.13
|   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity

- Crash 

--------------------------------------------------------

## Platforms you faced the error 

- iOS (14.7.1)

- Real device  (iPhone 11)

------------------------------------------------

**Bug description**
The app crashes when starting multiple instances of FlutterSoundPlayer:
───────────────────────────────────────────────────────────
[_aurioc] AURemoteIO.cpp:1097:Initialize: failed: -66635 (enable 3, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,      0 Hz, Float32>)
[avae]            **AVAEInternal.h:76    required condition is false: [AVAudioEngineGraph.mm:2128:_Connect: (IsFormatSampleRateAndChannelCountValid(format))]**
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: **IsFormatSampleRateAndChannelCountValid(format)**'
*** First throw call stack:
(0x1966a6708 0x1ab1b07a8 0x1965a83b8 0x1e3a39d2c 0x1e3a7cfd0 0x1e3a847e8 0x1e3b03820 0x1e3b05864 0x106554538 0x106551b30 0x10340b7c0 0x10340d7d8 0x106d72fd0 0x10685df6c 0x108cfc0b4 0x108cfdde0 0x108d0e0a8 0x196620340 0x19661a218 0x196619308 0x1adc9c734 0x19909775c 0x19909cfcc 0x1033defbc 0x1962d5cf8)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: **'required condition is false: IsFormatSampleRateAndChannelCountValid(format)'**
terminating with uncaught exception of type NSException_
───────────────────────────────────────────────────────────
I have had a similar crash before with FlutterSound Player and as many suggested setting the AVAudioSession category (in native objC code:`[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker error:&error];`) prior to calling .startPlayerFromStream() did in fact help remove this crash. However, when using multiple instances (two in this example), the AVAudioSession category remains the said one but the problem persists. 

**To Reproduce**
1. Create first instance of Flutter Sound Player
2. Create second instance of FSP
3. Call .openPlayer() on first instance
4. Call .openPlayer() on second instance
5. Call `startPlayerFromStream(codec: Codec.pcm16, sampleRate: 16000);` on first instance (the audio plays properly)
6. Call `startPlayerFromStream(codec: Codec.pcm16, sampleRate: 16000);` on second instance while the first one is still playing -> CRASH
7. See error
----------------------------------------------

# Logs!!!!

2022-05-25 23:23:55.012348+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.012367+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.012388+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.012501+0200 Runner[2426:1995871] flutter: │ 🐛 iOS: invokeMethod needSomeFood - state=1
2022-05-25 23:23:55.012563+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.012851+0200 Runner[2426:1995871] flutter: ┌───────────────────────────────────────────────────────────────
2022-05-25 23:23:55.012851+0200 Runner[2426:1995871] flutter: ┌───────────────────────────────────\342\224────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.012878+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.012899+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.012950+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.013034+0200 Runner[2426:1995871] flutter: │ 🐛 IOS:--> startPlayer
2022-05-25 23:23:55.013125+0200 Runner[2426:1995871] flutter: └──────────────────────┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.013034+0200 Runner[2426:1995871] flutter: │ 🐛 IOS:--> startPlayer
2022-05-25 23:23:55.013125+0200 Runner[2426:1995871] flutter: └──────────────────────\342\224─────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.013301+0200 Runner[2426:1995871] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.013368+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.013605+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.013844+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.013948+0200 Runner[2426:1995871] flutter: │ 🐛 IOS:--> startPlayer
2022-05-25 23:23:55.014042+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.014274+0200 Runner[2426:1995871] flutter: ┌────────────────────────────────────────────────────────────────────┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.013948+0200 Runner[2426:1995871] flutter: │ 🐛 IOS:--> startPlayer
2022-05-25 23:23:55.014042+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.014274+0200 Runner[2426:1995871] flutter: ┌────────────────────────────────────────────────────────────────────\342───────────────────────────────────────────────────
2022-05-25 23:23:55.014832+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.014854+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.014873+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.014890+0200 Runner[2426:1995871] flutter: │ ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.013948+0200 Runner[2426:1995871] flutter: │ 🐛 IOS:--> startPlayer
2022-05-25 23:23:55.014042+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.014274+0200 Runner[2426:1995871] flutter: ┌────────────────────────────────────────────────────────────────────\342───────────────────────────────────────────────────
2022-05-25 23:23:55.014832+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.014854+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.014873+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.014890+0200 Runner[2426:1995871] flutter: │ \360🐛 IOS:--> stopTimer
2022-05-25 23:23:55.014909+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.015416+0200 Runner[2426:1995871] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.015439+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.015458+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.015901+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-05-25 23:23:55.015922+0200 Runner[2426:1995871] flutter: │ 🐛 IOS:<-- stopTimer
2022-05-25 23:23:55.015942+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.017882+0200 Runner[2426:1995631] [aurioc] AURemoteIO.cpp:1097:Initialize: failed: -66635 (enable 3, outf< 1 ch,      0 Hz, Float32> inf< 1 ch,      0 Hz, Float32>)

2022-05-25 23:23:55.021026+0200 Runner[2426:1995631] [avae]            AVAEInternal.h:76    required condition is false: [AVAudioEngineGraph.mm:2128:_Connect: (IsFormatSampleRateAndChannelCountValid(format))]
2022-05-25 23:23:55.021150+0200 Runner[2426:1995871] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.021178+0200 Runner[2426:1995871] flutter: │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
2022-05-25 23:23:55.021200+0200 Runner[2426:1995871] flutter: │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
2022-05-25 23:23:55.021220+0200 Runner[2426:1995871] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
CallId: 2022-05-25 23:23:55.021264+0200 Runner[2426:1995871] flutter: │ 🐛 VoiceProcessing enabled
2022-05-25 23:23:55.021286+0200 Runner[2426:1995871] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-05-25 23:23:55.021537+0200 Runner[2426:1995631] *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: IsFormatSampleRateAndChannelCountValid(format)'
*** First throw call stack:
(0x1966a6708 0x1ab1b07a8 0x1965a83b8 0x1e3a39d2c 0x1e3a7cfd0 0x1e3a847e8 0x1e3b03820 0x1e3b05864 0x106554538 0x106551b30 0x10340b7c0 0x10340d7d8 0x106d72fd0 0x10685df6c 0x108cfc0b4 0x108cfdde0 0x108d0e0a8 0x196620340 0x19661a218 0x196619308 0x1adc9c734 0x19909775c 0x19909cfcc 0x1033defbc 0x1962d5cf8)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: IsFormatSampleRateAndChannelCountValid(format)'
terminating with uncaught exception of type NSException
(lldb) 

-----------------------------------------------------------------

**Comment by Vedranivic** [comment]
@Larpoux @hyochan @bsutton @JoniDS @ened @Mateis @mansya Can you please look into this issue?

**Comment by vedranivicatos** [comment]
I did some debugging of flutter_sound_core and flutter_sound source code and it turns out the critical error was `[aurioc] AURemoteIO.cpp:1097:Initialize: failed: -66635 (enable 3, outf< 1 ch, 0 Hz, Float32> inf< 1 ch, 0 Hz, Float32>)` which I think was thrown on FlautoPlayerEngine:179 -> `if (![outputNode setVoiceProcessingEnabled:YES error:&err]) {`. Commenting the voice processing enabling part of the code did the trick and multiple instances of FSP seem to work just fine. The underlying issue however is the bug where the voiceProcessingEnabled flag evaluates to true no matter what gets sent from the dart/app side (true or false). I have forked a repo and made a bug fix to map the voiceProcessingEnabled flag on iOS properly on objective C side and have created a Pull request.

**Comment by vedranivicatos** [comment]
This however is rather a patch not a real fix of the problem. The mention bug fix in PR is needed regardless. However, I believe the plugin needs some more investigation on why **multiple instances cannot work with voice processing enabled**, so I think this issue should remain open until resolved properly.

**Comment by ParhaMDeF** [comment]
I have this issue too. any update?
I used this package to play the streaming audio data from the microphone. here is the code:

```
  Future<void> _startStreaming() async {
    stream = await MicStream.microphone(
      sampleRate: 16000,
      channelConfig: ChannelConfig.CHANNEL_IN_MONO,
      audioFormat: AudioFormat.ENCODING_PCM_16BIT,
    );

    stream!.listen((Uint8List audioData) async {
      channel.sink.add(audioData);
      player = (await FlutterSoundPlayer()
          .openPlayer(enableVoiceProcessing: false))!;

      await player.startPlayer(
          codec: Codec.pcm16,
          numChannels: 1,
          sampleRate: 16000,
          fromDataBuffer: audioData);
    });
  }
```

**Comment by D10100111001** [comment]
how has no one run into this yet? I'm still getting issues? Why is this not fixed? Can we please get some movement on this? thanks! @Larpoux @hyochan @bsutton @JoniDS @ened @Mateis @mansya

**Comment by WNizard** [comment]
Hi @Larpoux it's been a while haha, I'm facing this type of issue too.
To remind you: I work on a babyphone with a remote server, and, while I'm on a call with my babyphone, I put the app on background, everything works perfectly, but if I receive a phone call and pick it up, the first time there is no issue, but the second time it crashes, with the same error as the issue! Do you have any visibility about this error? thank you very much as per usual!

**Comment by WNizard** [comment]
Hi @Larpoux,

The os is IOS, it works perfectly on Android (I'm not working with the web version)
I actually have this issue with the player, not the recorder so I can confirm that I call:
startPlayerFromStream()
and I also can confirm that I call player.openPlayer();
Check out the logs here:

![Screenshot 2024-12-05 at 10 00 36](https://github.com/user-attachments/assets/c929bb5b-5ddb-4d19-a048-6d65db4194d2)

**Comment by Larpoux** [comment]
I think that your problem is related with something I had to do to avoid this crash:
In the iOS code I had to insert this:
```dart
    if ((toStream != null ||
            toStreamFloat32 != null ||
            toStreamInt16 != null) &&
        (!kIsWeb) &&
        Platform
            .isIOS) // This hack is just to have recorder to stream working correctly.
    {
      FlutterSoundPlayer player = FlutterSoundPlayer();
      await player.openPlayer();
      Uint8List buf = Uint8List(0);
      //buf.fillRange(0, 1000, 0);
      try {
        await player.startPlayer(
            fromDataBuffer: buf, codec: Codec.pcm16, whenFinished: () {});
      } catch (e) {
        _logger.d('Hacking the bug we have on iOS when recording to stream');
      }
      //await player.stopPlayer();
      /* await */ player.closePlayer();
    }
```

I had fight during two weeks with this bug that I have never understood.
For some reason, the crash did not occur when I insert this hack. But this is just magic. This is not very understandable why this code suppress the crash. I am not very surprised that this patch does not always cure the issue.
It is possible that the crash is tied to an iOS bug (?)
But I give up with this problem. Sorry.

**Comment by Larpoux** [comment]
When I look to your traces, it seems that you `openPlayer()` and not `openPlayerFromStream`. Is it right ?

**Comment by Larpoux** [comment]
I am preparing a little hack for startPlayerFromStream(). I am not very confident that it will fix your issue, but you will be able to try it. It will be ready in half an hour. I will post you something when done.

**Comment by WNizard** [comment]
Thank you very much, I'il keep you in touch!

**Comment by Larpoux** [comment]
Flutter Sound version 9.17.6 is released
### 9.17.6

- on iOS : in playFromStream() add the same hack than with the recorder ([#900](https://github.com/Canardoux/flutter_sound/issues/900))

**Comment by WNizard** [comment]
I was previously using Flutter Sound version 9.4.11 because I used to use firebase_core and crashlytics 3.x.
Now that I upgraded everything I needed to, the app runs, but I can see that the audio doesn't work at ALL anymore, I have like 1 second of audio before everything breaks let's check out the logs:
![Screenshot 2024-12-05 at 12 51 23](https://github.com/user-attachments/assets/008cbc0f-7795-4743-885e-294f7d7923d3)
![Screenshot 2024-12-05 at 12 51 55](https://github.com/user-attachments/assets/93c45384-a0e7-4d4f-81e4-2ec928631d54)
![Screenshot 2024-12-05 at 12 52 09](https://github.com/user-attachments/assets/ddef965f-49d2-4265-bd93-45bc899e9933)
I have no clue about the reason why this happens, I'm going to try to downgrade flutterSound without downgrading firebase to check if the error is from the new update

**Comment by WNizard** [comment]
Yeah, I definetly have an issue with the foodSink since I upgraded it, even with flutter_sound9.17.5 it doesn't work anymore, let me figure out what is the latest version that works with my app!

**Comment by WNizard** [comment]
I implemented a test feature just to understand why nothing will play, can you please tell me why the new versions refuse to play sound this way?
![Screenshot 2024-12-05 at 13 54 09](https://github.com/user-attachments/assets/493fc685-1a84-4ced-bec3-80baf2a3bc08)

**Comment by WNizard** [comment]
After figuring out how to make the audio work again, I regret to tell you that the crash is still up:
"  AURemoteIO.cpp:1091  failed: 560557684 (enable 2, outf< 2 ch,      0 Hz, Float32, deinterleaved> inf< 2 ch,      0 Hz, Float32, deinterleaved>)
           AVAEInternal.h:71    required condition is false: [AVAudioEngineGraph.mm:2161:_Connect: (IsFormatSampleRateAndChannelCountValid(format))]
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: IsFormatSampleRateAndChannelCountValid(format)'
*** First throw call stack:
(0x1858447cc 0x182b172e4 0x18593f748 0x19fef5a60 0x19ffb7d30 0x19ffbbcf4 0x101ee0658 0x101eddcfc 0x100d21a00 0x100d23c2c 0x10549f210 0x104f20d88 0x10227ca30 0x10227e71c 0x10228ede8 0x10228e9a4 0x185818204 0x185815440 0x185814830 0x1d17f41c4 0x18837aeb0 0x1884295b4 0x188763fa8 0x100bfbd80 0x100bfbcf8 0x100bfbe2c 0x1ab202ec8)"

**Comment by Larpoux** [comment]
@WNizard ,
I am going to work on this issue during the next few days.
I need : 
- the sample rate that you use in your application 
- The number of channels (monophony, stereophony, …)
- The interlaced mode if the number of channels is > 1

**Comment by WNizard** [comment]
Thanks a lot for the support!
The sample rate is 16000, the number of channels : 1 
And the PCM is int 16!

**Comment by Larpoux** [comment]
@WNizard , Hi William,
could you try Flutter Sound 9.17.8 and send me the new logs if you still have crash ?
### 9.17.8

- On iOS : force output sampleRate to 48000 ([#900](https://github.com/Canardoux/flutter_sound/issues/900))

**Comment by WNizard** [comment]
Hi I don't have any remote access nor my working computer with me on the week ends!
I'Il get back to you on monday morning!

**Comment by WNizard** [comment]
@Larpoux , Hi Larpoux,
After making sure I did all the tests rights this morning, these are the logs I have after having the crash:
![Screenshot 2024-12-09 at 10 42 43](https://github.com/user-attachments/assets/929be9e5-aacd-4ea3-a179-85343e20f990)
Also I figured that I have to restart the acquirement of the audio player many times with the new versions and soundPlayer.startPlayerFromStream() throws many times,
If you need anything else tell me!

**Comment by Larpoux** [comment]
> but if I receive a phone call and pick it up, the first time there is no issue, but the second time it crashes, with the same error as the issue!

Does the new crash occur also after a phone call, or do you have the crash sooner or later ?

> Also I figured that I have to restart the acquirement of the audio player many times with the new versions and soundPlayer.startPlayerFromStream() throws many times,

I don't clearly understand what you mean

**Comment by WNizard** [comment]
It happens at the exact same time as before!
Let me explain the second point that you mentioned:
I'm currently using Flutter_sound 9.4.1, and, everything works perfectly except the issue that we are talking about right now.
with Flutter_sound 9.17.8 I also have other problems like some failures from soundPlayer.startPlayerFromStream() or sometimes the soundPlayer is reset to null, it's not any fatal errors because I juste have to call the method again every time it's reset to null but still it's an error that I had to report haha

**Comment by WNizard** [comment]
However, I found a way to not encounter the crash anymore: I created a swift method calling callkit to tell me when the user receives a phone call.
When it happens I dispose the audio session, set it to false and I wait for the call to end before starting again!

**Comment by Larpoux** [comment]
I am glad that you are not blocked anymore by this bug and that you will be able to release your product.
Of course your solution is just a turn around, but the bug is still there.
I am almost sure that I am fighting with bugs inside iOS.

**Comment by Larpoux** [comment]
Not sure to understand clearly your issue. 

Note 2 things : 
- On iOS there is only one session per app.
- Flutter Sound does not manage the iOS session. Please use another lib to do that. For example [audio_session](https://pub.dev/packages/audio_session)
