### ISSUE TITLE
[BUG]: No implementation found for method openPlayer on channel com.dooboolab.flutter_sound_player

### ISSUE THREAD

**Issue by good-good-study** [Canardoux/flutter_sound#901]
platform: macos 12.3.1
flutter_sound: ^9.2.13

<img width="767" alt="截屏2022-05-26 11 51 02" src="https://user-images.githubusercontent.com/20188392/170412469-b2401a26-d8d7-47ec-841f-878dcdca1311.png">

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method openPlayer on channel com.dooboolab.flutter_sound_player)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelFlutterSoundPlayer.invokeMethod (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:157:12)
<asynchronous suspension>
#2      FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:534:19)
<asynchronous suspension>
#3      FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:11)
<asynchronous suspension>

**Comment by zhou-candy** [comment]
This was fixed in 9.2.13

**Comment by good-good-study** [comment]
Version 9.2.13 still has this error
<img width="1561" alt="截屏2022-06-01 17 01 09" src="https://user-images.githubusercontent.com/20188392/171368280-4a180475-41a7-478a-8650-44d5b7cd8df1.png">

**Comment by Cartachana** [comment]
I have the same issue
<img width="499" alt="image" src="https://github.com/user-attachments/assets/3bc04829-8f7e-44e7-b2c8-6f9c26f5ae86">
