### ISSUE TITLE
[BUG]:Remote Url can't play in iOS and Andriod.

### ISSUE THREAD

**Issue by mozartee** [Canardoux/flutter_sound#968]
## Flutter Sound Version : v9.2.13

- **FULL** or **LITE** flavor ? 

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound```

----------------------------------------------------------

## Severity

- Crash ? false

- Result is not what expected ? true

- Cannot build my App ? false

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ? true

- Android ? true

- Flutter Web ? IDK

- Emulator ? true

- Real device ? true

------------------------------------------------

**Describe the bug**
There were two bugs I got:
1. In iOS Simulator, it could't record with any type of aac、mp4 etc, but real device success.
 the log is: Unhandled Exception: PlatformException(Audio Player, startPlayer failure, null, null)
2. It could't play remote url both of emulator and device, iOS or Andriod.

----------------------------------------------

# Logs!!!!
(**This is very important**. Most of the time we cannot do anything if we do not have information on your bug).
To activate the logs, you must instantiate your modules with the Log Level set to `Level.debug` :
```
FlutterSoundPlayer myPlayer = FlutterSoundPlayer(logLevel: Level.debug);
FlutterSoundRecorder myRecorder = FlutterSoundRecorder(logLevel: Level.debug);
```
See [this](https://tau.canardoux.xyz/logger.html)

some log like this:
E/MediaPlayerNative( 3932): error (1, -2147483648)
I/flutter ( 3932): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 3932): │ #0   FlutterSoundPlayer.log (package:flutter_sound/public/flutter_sound_player.dart:360:13)
flutter_sound_player.dart:360
I/flutter ( 3932): │ #1   MethodChannelFlutterSoundPlayer.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_player.dart:137:19)
method_channel_flutter_sound_player.dart:137
I/flutter ( 3932): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 3932): │ ⛔ startPlayer() exception
I/flutter ( 3932): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

:)

-----------------------------------------------------------------

**Comment by mozartee** [comment]
Pls ignore the second question,--!, the reason is the device was set proxy some days ago!!!

**Comment by zhaoxu666** [comment]
I have encountered the same problem, have you resolved it?
