### ISSUE TITLE
🐛 ctor: FlutterSoundRecorder()

### ISSUE THREAD

**Issue by joshua750** [Canardoux/flutter_sound#972]
hello when i try initialization sound recorder i am getting this error

import 'package:flutter_sound/flutter_sound.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:io';

class AudioController {
var _audioRecorder=FlutterSoundRecorder();
bool _isRecorderInitiated = false;

Future init() async {
  _audioRecorder = FlutterSoundRecorder();
  final status = await Permission.microphone.request();
  if (status != PermissionStatus.granted){
    throw RecordingPermissionException('Microphone permission denied.');
  }
  await _audioRecorder!.openRecorder();
  _isRecorderInitiated = true;
}

}

class Home extends StatefulWidget {

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {

  late bool isPlaying=false;
  AudioController audioController=new AudioController();
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    audioController.init();

  }

Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                           24.6s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Debug service listening on ws://127.0.0.1:61642/fZuqbTa-070=/ws
Syncing files to device iPhone 11...
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:140:13)
flutter: │ #1   new AudioController (package:voicerecoder/audiocontroller.dart:7:20)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 ctor: FlutterSoundRecorder()
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:140:13)
flutter: │ #1   AudioController.init (package:voicerecoder/audiocontroller.dart:11:20)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 ctor: FlutterSoundRecorder()
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'RecordingPermissionException'
#0      AudioController.init (package:voicerecoder/audiocontroller.dart:14:5)
<asynchronous suspension>

**Comment by triay0** [comment]
Have you added 
```

<key>NSMicrophoneUsageDescription</key>
<string>This app requires Mic permission.</string>
```

in Info.plist?

**Comment by joshua750** [comment]
i already give that permissions

**Comment by AumGupta** [comment]
@joshua750 you got any solution?

**Comment by joshua750** [comment]
simply i change the plugin using this record: ^5.0.1   developer is maintaining it

**Comment by WindsSunShine** [comment]
？？？

**Comment by MRasmussen2000** [comment]
Yes it does not activate permissions on iOS. There is some issue there so this needs to get fixed for cross platform ability
