### ISSUE TITLE
[HELP]:

### ISSUE THREAD

**Issue by opt289** [Canardoux/flutter_sound#982]
## For example the _Element_ τ room ?

------------

I need Help for :

- Using the API ?

- Generate an iOS or Android App ?

- Debugging my App ?

- Other ?
 flutter_sound: ^9.2.13
-------------------------------------
## Here is my question :

E/MethodChannel#com.dooboolab.flutter_sound_player(11083): Failed to handle method call
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at com.dooboolab.fluttersound.FlutterSoundManager.resetPlugin(FlutterSoundManager.java:88)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at com.dooboolab.fluttersound.FlutterSoundPlayerManager.onMethodCall(FlutterSoundPlayerManager.java:66)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at android.app.ActivityThread.main(ActivityThread.java:8136)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/MethodChannel#com.dooboolab.flutter_sound_player(11083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
E/DartMessenger(11083): Uncaught exception in binary message listener
E/DartMessenger(11083): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(11083): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/DartMessenger(11083): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:282)
E/DartMessenger(11083): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(11083): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(11083): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(11083): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger(11083): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(11083): 	at android.os.Looper.loopOnce(Looper.java:210)
E/DartMessenger(11083): 	at android.os.Looper.loop(Looper.java:299)
E/DartMessenger(11083): 	at android.app.ActivityThread.main(ActivityThread.java:8136)
E/DartMessenger(11083): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(11083): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/DartMessenger(11083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by opt289** [comment]
I used the official plugin flutter_sound, the latest example, and the debugger reported an error after that

**Comment by opt289** [comment]
![image](https://github.com/Canardoux/flutter_sound/assets/129495744/6ba704e1-ec6a-47aa-8b09-7cebe9250f17)
