### ISSUE TITLE
I want use flutter_sound in background[BUG]:

### ISSUE THREAD

**Issue by ImanGhasemiArani** [Canardoux/flutter_sound#995]
##### I want use player/recorder as stream in ```background_service``` in foreground mode. but when open player/recorder get exception that is ```MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_player)```.

 I tested it on android.

```
I/flutter (18930): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): │ #0   new FlutterSoundPlayer (package:flutter_sound/public/flutter_sound_player.dart:132:13)
I/flutter (18930): │ #1   BackgroundService.startCall.<anonymous closure> (package:wifoneapp/services/background_service.dart:176:36)
I/flutter (18930): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18930): │ 🐛 ctor: FlutterSoundPlayer()
I/flutter (18930): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:511:13)
I/flutter (18930): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:17)
I/flutter (18930): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18930): │ 🐛 FS:---> openAudioSession
I/flutter (18930): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (18930): │ #0   FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:524:15)
I/flutter (18930): │ #1   FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:17)
I/flutter (18930): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18930): │ 🐛 Resetting flutter_sound Player Plugin
I/flutter (18930): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (18930): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_player)
E/flutter (18930): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #1      FlutterSoundPlayer._openAudioSession (package:flutter_sound/public/flutter_sound_player.dart:526:7)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #2      FlutterSoundPlayer.openPlayer.<anonymous closure> (package:flutter_sound/public/flutter_sound_player.dart:504:11)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #4      FlutterSoundPlayer.openPlayer (package:flutter_sound/public/flutter_sound_player.dart:503:5)
E/flutter (18930): <asynchronous suspension>
E/flutter (18930): #5      BackgroundService.startCall.<anonymous closure> (package:wifoneapp/services/background_service.dart:177:7)
E/flutter (18930): <asynchronous suspension>
```

**Comment by Larpoux** [comment]
This issue must be analyzed

**Comment by ImanGhasemiArani** [comment]
> This issue must be analyzed

hello,
thanks for your reply. 
I solve that issue for recorder, recorder works fine in background (start recorder in background and use that in background). 
in implementation of native code of android, the initialize of player and recorder is in `onAttachedToActivity` but in background we don't have activity. and so need use `onAttachedToEngine` to initialize those. I initialize recorder in `onAttachedToEngine` and works fine, but player is not working.
